// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MediaAsset.proto

package com.mediaassetsdk;

public interface ApplyUploadResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApplyUploadResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string RequestID = 1;</code>
   * @return Whether the requestID field is set.
   */
  boolean hasRequestID();
  /**
   * <code>optional string RequestID = 1;</code>
   * @return The requestID.
   */
  java.lang.String getRequestID();
  /**
   * <code>optional string RequestID = 1;</code>
   * @return The bytes for requestID.
   */
  com.google.protobuf.ByteString
      getRequestIDBytes();

  /**
   * <code>optional .Error Error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>optional .Error Error = 2;</code>
   * @return The error.
   */
  com.mediaassetsdk.Error getError();
  /**
   * <code>optional .Error Error = 2;</code>
   */
  com.mediaassetsdk.ErrorOrBuilder getErrorOrBuilder();

  /**
   * <code>optional uint32 MediaID = 3;</code>
   * @return Whether the mediaID field is set.
   */
  boolean hasMediaID();
  /**
   * <code>optional uint32 MediaID = 3;</code>
   * @return The mediaID.
   */
  int getMediaID();

  /**
   * <code>optional string Key = 4;</code>
   * @return Whether the key field is set.
   */
  boolean hasKey();
  /**
   * <code>optional string Key = 4;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>optional string Key = 4;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>optional string Bucket = 5;</code>
   * @return Whether the bucket field is set.
   */
  boolean hasBucket();
  /**
   * <code>optional string Bucket = 5;</code>
   * @return The bucket.
   */
  java.lang.String getBucket();
  /**
   * <code>optional string Bucket = 5;</code>
   * @return The bytes for bucket.
   */
  com.google.protobuf.ByteString
      getBucketBytes();

  /**
   * <code>optional string UploadId = 6;</code>
   * @return Whether the uploadId field is set.
   */
  boolean hasUploadId();
  /**
   * <code>optional string UploadId = 6;</code>
   * @return The uploadId.
   */
  java.lang.String getUploadId();
  /**
   * <code>optional string UploadId = 6;</code>
   * @return The bytes for uploadId.
   */
  com.google.protobuf.ByteString
      getUploadIdBytes();
}
