// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MediaAsset.proto

package com.mediaassetsdk;

public interface CreateMediasResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateMediasResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string RequestID = 1;</code>
   * @return Whether the requestID field is set.
   */
  boolean hasRequestID();
  /**
   * <code>optional string RequestID = 1;</code>
   * @return The requestID.
   */
  java.lang.String getRequestID();
  /**
   * <code>optional string RequestID = 1;</code>
   * @return The bytes for requestID.
   */
  com.google.protobuf.ByteString
      getRequestIDBytes();

  /**
   * <code>optional .Error Error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>optional .Error Error = 2;</code>
   * @return The error.
   */
  com.mediaassetsdk.Error getError();
  /**
   * <code>optional .Error Error = 2;</code>
   */
  com.mediaassetsdk.ErrorOrBuilder getErrorOrBuilder();

  /**
   * <code>repeated .UploadMediaInfo UploadMediaInfoSet = 3;</code>
   */
  java.util.List<com.mediaassetsdk.UploadMediaInfo> 
      getUploadMediaInfoSetList();
  /**
   * <code>repeated .UploadMediaInfo UploadMediaInfoSet = 3;</code>
   */
  com.mediaassetsdk.UploadMediaInfo getUploadMediaInfoSet(int index);
  /**
   * <code>repeated .UploadMediaInfo UploadMediaInfoSet = 3;</code>
   */
  int getUploadMediaInfoSetCount();
  /**
   * <code>repeated .UploadMediaInfo UploadMediaInfoSet = 3;</code>
   */
  java.util.List<? extends com.mediaassetsdk.UploadMediaInfoOrBuilder> 
      getUploadMediaInfoSetOrBuilderList();
  /**
   * <code>repeated .UploadMediaInfo UploadMediaInfoSet = 3;</code>
   */
  com.mediaassetsdk.UploadMediaInfoOrBuilder getUploadMediaInfoSetOrBuilder(
      int index);
}
