// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MediaAsset.proto

package com.mediaassetsdk;

public interface DescribeMediasRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DescribeMediasRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string Action = 1;</code>
   * @return Whether the action field is set.
   */
  boolean hasAction();
  /**
   * <code>optional string Action = 1;</code>
   * @return The action.
   */
  java.lang.String getAction();
  /**
   * <code>optional string Action = 1;</code>
   * @return The bytes for action.
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <code>optional int32 TIBusinessID = 2;</code>
   * @return Whether the tIBusinessID field is set.
   */
  boolean hasTIBusinessID();
  /**
   * <code>optional int32 TIBusinessID = 2;</code>
   * @return The tIBusinessID.
   */
  int getTIBusinessID();

  /**
   * <code>optional int32 TIProjectID = 3;</code>
   * @return Whether the tIProjectID field is set.
   */
  boolean hasTIProjectID();
  /**
   * <code>optional int32 TIProjectID = 3;</code>
   * @return The tIProjectID.
   */
  int getTIProjectID();

  /**
   * <code>optional int32 PageNumber = 4;</code>
   * @return Whether the pageNumber field is set.
   */
  boolean hasPageNumber();
  /**
   * <code>optional int32 PageNumber = 4;</code>
   * @return The pageNumber.
   */
  int getPageNumber();

  /**
   * <code>optional int32 PageSize = 5;</code>
   * @return Whether the pageSize field is set.
   */
  boolean hasPageSize();
  /**
   * <code>optional int32 PageSize = 5;</code>
   * @return The pageSize.
   */
  int getPageSize();

  /**
   * <code>optional bool Inner = 6;</code>
   * @return Whether the inner field is set.
   */
  boolean hasInner();
  /**
   * <code>optional bool Inner = 6;</code>
   * @return The inner.
   */
  boolean getInner();

  /**
   * <code>optional .FilterBy FilterBy = 7;</code>
   * @return Whether the filterBy field is set.
   */
  boolean hasFilterBy();
  /**
   * <code>optional .FilterBy FilterBy = 7;</code>
   * @return The filterBy.
   */
  com.mediaassetsdk.FilterBy getFilterBy();
  /**
   * <code>optional .FilterBy FilterBy = 7;</code>
   */
  com.mediaassetsdk.FilterByOrBuilder getFilterByOrBuilder();
}
