// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MediaAsset.proto

package com.mediaassetsdk;

/**
 * Protobuf type {@code DescribeMediasResponse}
 */
public final class DescribeMediasResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:DescribeMediasResponse)
    DescribeMediasResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DescribeMediasResponse.newBuilder() to construct.
  private DescribeMediasResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DescribeMediasResponse() {
    requestID_ = "";
    mediaInfoSet_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DescribeMediasResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DescribeMediasResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            requestID_ = s;
            break;
          }
          case 18: {
            com.mediaassetsdk.Error.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) != 0)) {
              subBuilder = error_.toBuilder();
            }
            error_ = input.readMessage(com.mediaassetsdk.Error.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(error_);
              error_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              mediaInfoSet_ = new java.util.ArrayList<com.mediaassetsdk.MediaInfo>();
              mutable_bitField0_ |= 0x00000004;
            }
            mediaInfoSet_.add(
                input.readMessage(com.mediaassetsdk.MediaInfo.parser(), extensionRegistry));
            break;
          }
          case 32: {
            bitField0_ |= 0x00000004;
            totalCount_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        mediaInfoSet_ = java.util.Collections.unmodifiableList(mediaInfoSet_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mediaassetsdk.MediaAsset.internal_static_DescribeMediasResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mediaassetsdk.MediaAsset.internal_static_DescribeMediasResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mediaassetsdk.DescribeMediasResponse.class, com.mediaassetsdk.DescribeMediasResponse.Builder.class);
  }

  private int bitField0_;
  public static final int REQUESTID_FIELD_NUMBER = 1;
  private volatile java.lang.Object requestID_;
  /**
   * <code>optional string RequestID = 1;</code>
   * @return Whether the requestID field is set.
   */
  @java.lang.Override
  public boolean hasRequestID() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string RequestID = 1;</code>
   * @return The requestID.
   */
  @java.lang.Override
  public java.lang.String getRequestID() {
    java.lang.Object ref = requestID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestID_ = s;
      return s;
    }
  }
  /**
   * <code>optional string RequestID = 1;</code>
   * @return The bytes for requestID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestIDBytes() {
    java.lang.Object ref = requestID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERROR_FIELD_NUMBER = 2;
  private com.mediaassetsdk.Error error_;
  /**
   * <code>optional .Error Error = 2;</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .Error Error = 2;</code>
   * @return The error.
   */
  @java.lang.Override
  public com.mediaassetsdk.Error getError() {
    return error_ == null ? com.mediaassetsdk.Error.getDefaultInstance() : error_;
  }
  /**
   * <code>optional .Error Error = 2;</code>
   */
  @java.lang.Override
  public com.mediaassetsdk.ErrorOrBuilder getErrorOrBuilder() {
    return error_ == null ? com.mediaassetsdk.Error.getDefaultInstance() : error_;
  }

  public static final int MEDIAINFOSET_FIELD_NUMBER = 3;
  private java.util.List<com.mediaassetsdk.MediaInfo> mediaInfoSet_;
  /**
   * <code>repeated .MediaInfo MediaInfoSet = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.mediaassetsdk.MediaInfo> getMediaInfoSetList() {
    return mediaInfoSet_;
  }
  /**
   * <code>repeated .MediaInfo MediaInfoSet = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.mediaassetsdk.MediaInfoOrBuilder> 
      getMediaInfoSetOrBuilderList() {
    return mediaInfoSet_;
  }
  /**
   * <code>repeated .MediaInfo MediaInfoSet = 3;</code>
   */
  @java.lang.Override
  public int getMediaInfoSetCount() {
    return mediaInfoSet_.size();
  }
  /**
   * <code>repeated .MediaInfo MediaInfoSet = 3;</code>
   */
  @java.lang.Override
  public com.mediaassetsdk.MediaInfo getMediaInfoSet(int index) {
    return mediaInfoSet_.get(index);
  }
  /**
   * <code>repeated .MediaInfo MediaInfoSet = 3;</code>
   */
  @java.lang.Override
  public com.mediaassetsdk.MediaInfoOrBuilder getMediaInfoSetOrBuilder(
      int index) {
    return mediaInfoSet_.get(index);
  }

  public static final int TOTALCOUNT_FIELD_NUMBER = 4;
  private int totalCount_;
  /**
   * <code>optional int32 TotalCount = 4;</code>
   * @return Whether the totalCount field is set.
   */
  @java.lang.Override
  public boolean hasTotalCount() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int32 TotalCount = 4;</code>
   * @return The totalCount.
   */
  @java.lang.Override
  public int getTotalCount() {
    return totalCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestID_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getError());
    }
    for (int i = 0; i < mediaInfoSet_.size(); i++) {
      output.writeMessage(3, mediaInfoSet_.get(i));
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(4, totalCount_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestID_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getError());
    }
    for (int i = 0; i < mediaInfoSet_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, mediaInfoSet_.get(i));
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, totalCount_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mediaassetsdk.DescribeMediasResponse)) {
      return super.equals(obj);
    }
    com.mediaassetsdk.DescribeMediasResponse other = (com.mediaassetsdk.DescribeMediasResponse) obj;

    if (hasRequestID() != other.hasRequestID()) return false;
    if (hasRequestID()) {
      if (!getRequestID()
          .equals(other.getRequestID())) return false;
    }
    if (hasError() != other.hasError()) return false;
    if (hasError()) {
      if (!getError()
          .equals(other.getError())) return false;
    }
    if (!getMediaInfoSetList()
        .equals(other.getMediaInfoSetList())) return false;
    if (hasTotalCount() != other.hasTotalCount()) return false;
    if (hasTotalCount()) {
      if (getTotalCount()
          != other.getTotalCount()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRequestID()) {
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestID().hashCode();
    }
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    if (getMediaInfoSetCount() > 0) {
      hash = (37 * hash) + MEDIAINFOSET_FIELD_NUMBER;
      hash = (53 * hash) + getMediaInfoSetList().hashCode();
    }
    if (hasTotalCount()) {
      hash = (37 * hash) + TOTALCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getTotalCount();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mediaassetsdk.DescribeMediasResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mediaassetsdk.DescribeMediasResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mediaassetsdk.DescribeMediasResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mediaassetsdk.DescribeMediasResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mediaassetsdk.DescribeMediasResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mediaassetsdk.DescribeMediasResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mediaassetsdk.DescribeMediasResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mediaassetsdk.DescribeMediasResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mediaassetsdk.DescribeMediasResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.mediaassetsdk.DescribeMediasResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mediaassetsdk.DescribeMediasResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mediaassetsdk.DescribeMediasResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mediaassetsdk.DescribeMediasResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code DescribeMediasResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DescribeMediasResponse)
      com.mediaassetsdk.DescribeMediasResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mediaassetsdk.MediaAsset.internal_static_DescribeMediasResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mediaassetsdk.MediaAsset.internal_static_DescribeMediasResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mediaassetsdk.DescribeMediasResponse.class, com.mediaassetsdk.DescribeMediasResponse.Builder.class);
    }

    // Construct using com.mediaassetsdk.DescribeMediasResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getErrorFieldBuilder();
        getMediaInfoSetFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      requestID_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      if (errorBuilder_ == null) {
        error_ = null;
      } else {
        errorBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (mediaInfoSetBuilder_ == null) {
        mediaInfoSet_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        mediaInfoSetBuilder_.clear();
      }
      totalCount_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mediaassetsdk.MediaAsset.internal_static_DescribeMediasResponse_descriptor;
    }

    @java.lang.Override
    public com.mediaassetsdk.DescribeMediasResponse getDefaultInstanceForType() {
      return com.mediaassetsdk.DescribeMediasResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.mediaassetsdk.DescribeMediasResponse build() {
      com.mediaassetsdk.DescribeMediasResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mediaassetsdk.DescribeMediasResponse buildPartial() {
      com.mediaassetsdk.DescribeMediasResponse result = new com.mediaassetsdk.DescribeMediasResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.requestID_ = requestID_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        if (errorBuilder_ == null) {
          result.error_ = error_;
        } else {
          result.error_ = errorBuilder_.build();
        }
        to_bitField0_ |= 0x00000002;
      }
      if (mediaInfoSetBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          mediaInfoSet_ = java.util.Collections.unmodifiableList(mediaInfoSet_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.mediaInfoSet_ = mediaInfoSet_;
      } else {
        result.mediaInfoSet_ = mediaInfoSetBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.totalCount_ = totalCount_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mediaassetsdk.DescribeMediasResponse) {
        return mergeFrom((com.mediaassetsdk.DescribeMediasResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mediaassetsdk.DescribeMediasResponse other) {
      if (other == com.mediaassetsdk.DescribeMediasResponse.getDefaultInstance()) return this;
      if (other.hasRequestID()) {
        bitField0_ |= 0x00000001;
        requestID_ = other.requestID_;
        onChanged();
      }
      if (other.hasError()) {
        mergeError(other.getError());
      }
      if (mediaInfoSetBuilder_ == null) {
        if (!other.mediaInfoSet_.isEmpty()) {
          if (mediaInfoSet_.isEmpty()) {
            mediaInfoSet_ = other.mediaInfoSet_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureMediaInfoSetIsMutable();
            mediaInfoSet_.addAll(other.mediaInfoSet_);
          }
          onChanged();
        }
      } else {
        if (!other.mediaInfoSet_.isEmpty()) {
          if (mediaInfoSetBuilder_.isEmpty()) {
            mediaInfoSetBuilder_.dispose();
            mediaInfoSetBuilder_ = null;
            mediaInfoSet_ = other.mediaInfoSet_;
            bitField0_ = (bitField0_ & ~0x00000004);
            mediaInfoSetBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMediaInfoSetFieldBuilder() : null;
          } else {
            mediaInfoSetBuilder_.addAllMessages(other.mediaInfoSet_);
          }
        }
      }
      if (other.hasTotalCount()) {
        setTotalCount(other.getTotalCount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.mediaassetsdk.DescribeMediasResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.mediaassetsdk.DescribeMediasResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object requestID_ = "";
    /**
     * <code>optional string RequestID = 1;</code>
     * @return Whether the requestID field is set.
     */
    public boolean hasRequestID() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string RequestID = 1;</code>
     * @return The requestID.
     */
    public java.lang.String getRequestID() {
      java.lang.Object ref = requestID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string RequestID = 1;</code>
     * @return The bytes for requestID.
     */
    public com.google.protobuf.ByteString
        getRequestIDBytes() {
      java.lang.Object ref = requestID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string RequestID = 1;</code>
     * @param value The requestID to set.
     * @return This builder for chaining.
     */
    public Builder setRequestID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      requestID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string RequestID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestID() {
      bitField0_ = (bitField0_ & ~0x00000001);
      requestID_ = getDefaultInstance().getRequestID();
      onChanged();
      return this;
    }
    /**
     * <code>optional string RequestID = 1;</code>
     * @param value The bytes for requestID to set.
     * @return This builder for chaining.
     */
    public Builder setRequestIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      requestID_ = value;
      onChanged();
      return this;
    }

    private com.mediaassetsdk.Error error_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mediaassetsdk.Error, com.mediaassetsdk.Error.Builder, com.mediaassetsdk.ErrorOrBuilder> errorBuilder_;
    /**
     * <code>optional .Error Error = 2;</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .Error Error = 2;</code>
     * @return The error.
     */
    public com.mediaassetsdk.Error getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? com.mediaassetsdk.Error.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .Error Error = 2;</code>
     */
    public Builder setError(com.mediaassetsdk.Error value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .Error Error = 2;</code>
     */
    public Builder setError(
        com.mediaassetsdk.Error.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .Error Error = 2;</code>
     */
    public Builder mergeError(com.mediaassetsdk.Error value) {
      if (errorBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
            error_ != null &&
            error_ != com.mediaassetsdk.Error.getDefaultInstance()) {
          error_ =
            com.mediaassetsdk.Error.newBuilder(error_).mergeFrom(value).buildPartial();
        } else {
          error_ = value;
        }
        onChanged();
      } else {
        errorBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .Error Error = 2;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        error_ = null;
        onChanged();
      } else {
        errorBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>optional .Error Error = 2;</code>
     */
    public com.mediaassetsdk.Error.Builder getErrorBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .Error Error = 2;</code>
     */
    public com.mediaassetsdk.ErrorOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            com.mediaassetsdk.Error.getDefaultInstance() : error_;
      }
    }
    /**
     * <code>optional .Error Error = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mediaassetsdk.Error, com.mediaassetsdk.Error.Builder, com.mediaassetsdk.ErrorOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mediaassetsdk.Error, com.mediaassetsdk.Error.Builder, com.mediaassetsdk.ErrorOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }

    private java.util.List<com.mediaassetsdk.MediaInfo> mediaInfoSet_ =
      java.util.Collections.emptyList();
    private void ensureMediaInfoSetIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        mediaInfoSet_ = new java.util.ArrayList<com.mediaassetsdk.MediaInfo>(mediaInfoSet_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.mediaassetsdk.MediaInfo, com.mediaassetsdk.MediaInfo.Builder, com.mediaassetsdk.MediaInfoOrBuilder> mediaInfoSetBuilder_;

    /**
     * <code>repeated .MediaInfo MediaInfoSet = 3;</code>
     */
    public java.util.List<com.mediaassetsdk.MediaInfo> getMediaInfoSetList() {
      if (mediaInfoSetBuilder_ == null) {
        return java.util.Collections.unmodifiableList(mediaInfoSet_);
      } else {
        return mediaInfoSetBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .MediaInfo MediaInfoSet = 3;</code>
     */
    public int getMediaInfoSetCount() {
      if (mediaInfoSetBuilder_ == null) {
        return mediaInfoSet_.size();
      } else {
        return mediaInfoSetBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .MediaInfo MediaInfoSet = 3;</code>
     */
    public com.mediaassetsdk.MediaInfo getMediaInfoSet(int index) {
      if (mediaInfoSetBuilder_ == null) {
        return mediaInfoSet_.get(index);
      } else {
        return mediaInfoSetBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .MediaInfo MediaInfoSet = 3;</code>
     */
    public Builder setMediaInfoSet(
        int index, com.mediaassetsdk.MediaInfo value) {
      if (mediaInfoSetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMediaInfoSetIsMutable();
        mediaInfoSet_.set(index, value);
        onChanged();
      } else {
        mediaInfoSetBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MediaInfo MediaInfoSet = 3;</code>
     */
    public Builder setMediaInfoSet(
        int index, com.mediaassetsdk.MediaInfo.Builder builderForValue) {
      if (mediaInfoSetBuilder_ == null) {
        ensureMediaInfoSetIsMutable();
        mediaInfoSet_.set(index, builderForValue.build());
        onChanged();
      } else {
        mediaInfoSetBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MediaInfo MediaInfoSet = 3;</code>
     */
    public Builder addMediaInfoSet(com.mediaassetsdk.MediaInfo value) {
      if (mediaInfoSetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMediaInfoSetIsMutable();
        mediaInfoSet_.add(value);
        onChanged();
      } else {
        mediaInfoSetBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .MediaInfo MediaInfoSet = 3;</code>
     */
    public Builder addMediaInfoSet(
        int index, com.mediaassetsdk.MediaInfo value) {
      if (mediaInfoSetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMediaInfoSetIsMutable();
        mediaInfoSet_.add(index, value);
        onChanged();
      } else {
        mediaInfoSetBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MediaInfo MediaInfoSet = 3;</code>
     */
    public Builder addMediaInfoSet(
        com.mediaassetsdk.MediaInfo.Builder builderForValue) {
      if (mediaInfoSetBuilder_ == null) {
        ensureMediaInfoSetIsMutable();
        mediaInfoSet_.add(builderForValue.build());
        onChanged();
      } else {
        mediaInfoSetBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MediaInfo MediaInfoSet = 3;</code>
     */
    public Builder addMediaInfoSet(
        int index, com.mediaassetsdk.MediaInfo.Builder builderForValue) {
      if (mediaInfoSetBuilder_ == null) {
        ensureMediaInfoSetIsMutable();
        mediaInfoSet_.add(index, builderForValue.build());
        onChanged();
      } else {
        mediaInfoSetBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MediaInfo MediaInfoSet = 3;</code>
     */
    public Builder addAllMediaInfoSet(
        java.lang.Iterable<? extends com.mediaassetsdk.MediaInfo> values) {
      if (mediaInfoSetBuilder_ == null) {
        ensureMediaInfoSetIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, mediaInfoSet_);
        onChanged();
      } else {
        mediaInfoSetBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .MediaInfo MediaInfoSet = 3;</code>
     */
    public Builder clearMediaInfoSet() {
      if (mediaInfoSetBuilder_ == null) {
        mediaInfoSet_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        mediaInfoSetBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .MediaInfo MediaInfoSet = 3;</code>
     */
    public Builder removeMediaInfoSet(int index) {
      if (mediaInfoSetBuilder_ == null) {
        ensureMediaInfoSetIsMutable();
        mediaInfoSet_.remove(index);
        onChanged();
      } else {
        mediaInfoSetBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .MediaInfo MediaInfoSet = 3;</code>
     */
    public com.mediaassetsdk.MediaInfo.Builder getMediaInfoSetBuilder(
        int index) {
      return getMediaInfoSetFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .MediaInfo MediaInfoSet = 3;</code>
     */
    public com.mediaassetsdk.MediaInfoOrBuilder getMediaInfoSetOrBuilder(
        int index) {
      if (mediaInfoSetBuilder_ == null) {
        return mediaInfoSet_.get(index);  } else {
        return mediaInfoSetBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .MediaInfo MediaInfoSet = 3;</code>
     */
    public java.util.List<? extends com.mediaassetsdk.MediaInfoOrBuilder> 
         getMediaInfoSetOrBuilderList() {
      if (mediaInfoSetBuilder_ != null) {
        return mediaInfoSetBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(mediaInfoSet_);
      }
    }
    /**
     * <code>repeated .MediaInfo MediaInfoSet = 3;</code>
     */
    public com.mediaassetsdk.MediaInfo.Builder addMediaInfoSetBuilder() {
      return getMediaInfoSetFieldBuilder().addBuilder(
          com.mediaassetsdk.MediaInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .MediaInfo MediaInfoSet = 3;</code>
     */
    public com.mediaassetsdk.MediaInfo.Builder addMediaInfoSetBuilder(
        int index) {
      return getMediaInfoSetFieldBuilder().addBuilder(
          index, com.mediaassetsdk.MediaInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .MediaInfo MediaInfoSet = 3;</code>
     */
    public java.util.List<com.mediaassetsdk.MediaInfo.Builder> 
         getMediaInfoSetBuilderList() {
      return getMediaInfoSetFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.mediaassetsdk.MediaInfo, com.mediaassetsdk.MediaInfo.Builder, com.mediaassetsdk.MediaInfoOrBuilder> 
        getMediaInfoSetFieldBuilder() {
      if (mediaInfoSetBuilder_ == null) {
        mediaInfoSetBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.mediaassetsdk.MediaInfo, com.mediaassetsdk.MediaInfo.Builder, com.mediaassetsdk.MediaInfoOrBuilder>(
                mediaInfoSet_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        mediaInfoSet_ = null;
      }
      return mediaInfoSetBuilder_;
    }

    private int totalCount_ ;
    /**
     * <code>optional int32 TotalCount = 4;</code>
     * @return Whether the totalCount field is set.
     */
    @java.lang.Override
    public boolean hasTotalCount() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 TotalCount = 4;</code>
     * @return The totalCount.
     */
    @java.lang.Override
    public int getTotalCount() {
      return totalCount_;
    }
    /**
     * <code>optional int32 TotalCount = 4;</code>
     * @param value The totalCount to set.
     * @return This builder for chaining.
     */
    public Builder setTotalCount(int value) {
      bitField0_ |= 0x00000008;
      totalCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 TotalCount = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalCount() {
      bitField0_ = (bitField0_ & ~0x00000008);
      totalCount_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:DescribeMediasResponse)
  }

  // @@protoc_insertion_point(class_scope:DescribeMediasResponse)
  private static final com.mediaassetsdk.DescribeMediasResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mediaassetsdk.DescribeMediasResponse();
  }

  public static com.mediaassetsdk.DescribeMediasResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DescribeMediasResponse>
      PARSER = new com.google.protobuf.AbstractParser<DescribeMediasResponse>() {
    @java.lang.Override
    public DescribeMediasResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DescribeMediasResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DescribeMediasResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DescribeMediasResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mediaassetsdk.DescribeMediasResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

