// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MediaAsset.proto

package com.mediaassetsdk;

/**
 * Protobuf type {@code DescribeCategoriesResponse}
 */
public final class DescribeCategoriesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:DescribeCategoriesResponse)
    DescribeCategoriesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DescribeCategoriesResponse.newBuilder() to construct.
  private DescribeCategoriesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DescribeCategoriesResponse() {
    requestID_ = "";
    categorySet_ = java.util.Collections.emptyList();
    labelSet_ = java.util.Collections.emptyList();
    langSet_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DescribeCategoriesResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DescribeCategoriesResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            requestID_ = s;
            break;
          }
          case 18: {
            com.mediaassetsdk.Error.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) != 0)) {
              subBuilder = error_.toBuilder();
            }
            error_ = input.readMessage(com.mediaassetsdk.Error.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(error_);
              error_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              categorySet_ = new java.util.ArrayList<com.mediaassetsdk.Category>();
              mutable_bitField0_ |= 0x00000004;
            }
            categorySet_.add(
                input.readMessage(com.mediaassetsdk.Category.parser(), extensionRegistry));
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              labelSet_ = new java.util.ArrayList<com.mediaassetsdk.Label>();
              mutable_bitField0_ |= 0x00000008;
            }
            labelSet_.add(
                input.readMessage(com.mediaassetsdk.Label.parser(), extensionRegistry));
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000010) != 0)) {
              langSet_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000010;
            }
            langSet_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        categorySet_ = java.util.Collections.unmodifiableList(categorySet_);
      }
      if (((mutable_bitField0_ & 0x00000008) != 0)) {
        labelSet_ = java.util.Collections.unmodifiableList(labelSet_);
      }
      if (((mutable_bitField0_ & 0x00000010) != 0)) {
        langSet_ = langSet_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mediaassetsdk.MediaAsset.internal_static_DescribeCategoriesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mediaassetsdk.MediaAsset.internal_static_DescribeCategoriesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mediaassetsdk.DescribeCategoriesResponse.class, com.mediaassetsdk.DescribeCategoriesResponse.Builder.class);
  }

  private int bitField0_;
  public static final int REQUESTID_FIELD_NUMBER = 1;
  private volatile java.lang.Object requestID_;
  /**
   * <code>optional string RequestID = 1;</code>
   * @return Whether the requestID field is set.
   */
  @java.lang.Override
  public boolean hasRequestID() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string RequestID = 1;</code>
   * @return The requestID.
   */
  @java.lang.Override
  public java.lang.String getRequestID() {
    java.lang.Object ref = requestID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestID_ = s;
      return s;
    }
  }
  /**
   * <code>optional string RequestID = 1;</code>
   * @return The bytes for requestID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestIDBytes() {
    java.lang.Object ref = requestID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERROR_FIELD_NUMBER = 2;
  private com.mediaassetsdk.Error error_;
  /**
   * <code>optional .Error Error = 2;</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .Error Error = 2;</code>
   * @return The error.
   */
  @java.lang.Override
  public com.mediaassetsdk.Error getError() {
    return error_ == null ? com.mediaassetsdk.Error.getDefaultInstance() : error_;
  }
  /**
   * <code>optional .Error Error = 2;</code>
   */
  @java.lang.Override
  public com.mediaassetsdk.ErrorOrBuilder getErrorOrBuilder() {
    return error_ == null ? com.mediaassetsdk.Error.getDefaultInstance() : error_;
  }

  public static final int CATEGORYSET_FIELD_NUMBER = 3;
  private java.util.List<com.mediaassetsdk.Category> categorySet_;
  /**
   * <code>repeated .Category CategorySet = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.mediaassetsdk.Category> getCategorySetList() {
    return categorySet_;
  }
  /**
   * <code>repeated .Category CategorySet = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.mediaassetsdk.CategoryOrBuilder> 
      getCategorySetOrBuilderList() {
    return categorySet_;
  }
  /**
   * <code>repeated .Category CategorySet = 3;</code>
   */
  @java.lang.Override
  public int getCategorySetCount() {
    return categorySet_.size();
  }
  /**
   * <code>repeated .Category CategorySet = 3;</code>
   */
  @java.lang.Override
  public com.mediaassetsdk.Category getCategorySet(int index) {
    return categorySet_.get(index);
  }
  /**
   * <code>repeated .Category CategorySet = 3;</code>
   */
  @java.lang.Override
  public com.mediaassetsdk.CategoryOrBuilder getCategorySetOrBuilder(
      int index) {
    return categorySet_.get(index);
  }

  public static final int LABELSET_FIELD_NUMBER = 4;
  private java.util.List<com.mediaassetsdk.Label> labelSet_;
  /**
   * <code>repeated .Label LabelSet = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.mediaassetsdk.Label> getLabelSetList() {
    return labelSet_;
  }
  /**
   * <code>repeated .Label LabelSet = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.mediaassetsdk.LabelOrBuilder> 
      getLabelSetOrBuilderList() {
    return labelSet_;
  }
  /**
   * <code>repeated .Label LabelSet = 4;</code>
   */
  @java.lang.Override
  public int getLabelSetCount() {
    return labelSet_.size();
  }
  /**
   * <code>repeated .Label LabelSet = 4;</code>
   */
  @java.lang.Override
  public com.mediaassetsdk.Label getLabelSet(int index) {
    return labelSet_.get(index);
  }
  /**
   * <code>repeated .Label LabelSet = 4;</code>
   */
  @java.lang.Override
  public com.mediaassetsdk.LabelOrBuilder getLabelSetOrBuilder(
      int index) {
    return labelSet_.get(index);
  }

  public static final int LANGSET_FIELD_NUMBER = 5;
  private com.google.protobuf.LazyStringList langSet_;
  /**
   * <code>repeated string LangSet = 5;</code>
   * @return A list containing the langSet.
   */
  public com.google.protobuf.ProtocolStringList
      getLangSetList() {
    return langSet_;
  }
  /**
   * <code>repeated string LangSet = 5;</code>
   * @return The count of langSet.
   */
  public int getLangSetCount() {
    return langSet_.size();
  }
  /**
   * <code>repeated string LangSet = 5;</code>
   * @param index The index of the element to return.
   * @return The langSet at the given index.
   */
  public java.lang.String getLangSet(int index) {
    return langSet_.get(index);
  }
  /**
   * <code>repeated string LangSet = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the langSet at the given index.
   */
  public com.google.protobuf.ByteString
      getLangSetBytes(int index) {
    return langSet_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestID_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getError());
    }
    for (int i = 0; i < categorySet_.size(); i++) {
      output.writeMessage(3, categorySet_.get(i));
    }
    for (int i = 0; i < labelSet_.size(); i++) {
      output.writeMessage(4, labelSet_.get(i));
    }
    for (int i = 0; i < langSet_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, langSet_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestID_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getError());
    }
    for (int i = 0; i < categorySet_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, categorySet_.get(i));
    }
    for (int i = 0; i < labelSet_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, labelSet_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < langSet_.size(); i++) {
        dataSize += computeStringSizeNoTag(langSet_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getLangSetList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mediaassetsdk.DescribeCategoriesResponse)) {
      return super.equals(obj);
    }
    com.mediaassetsdk.DescribeCategoriesResponse other = (com.mediaassetsdk.DescribeCategoriesResponse) obj;

    if (hasRequestID() != other.hasRequestID()) return false;
    if (hasRequestID()) {
      if (!getRequestID()
          .equals(other.getRequestID())) return false;
    }
    if (hasError() != other.hasError()) return false;
    if (hasError()) {
      if (!getError()
          .equals(other.getError())) return false;
    }
    if (!getCategorySetList()
        .equals(other.getCategorySetList())) return false;
    if (!getLabelSetList()
        .equals(other.getLabelSetList())) return false;
    if (!getLangSetList()
        .equals(other.getLangSetList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRequestID()) {
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestID().hashCode();
    }
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    if (getCategorySetCount() > 0) {
      hash = (37 * hash) + CATEGORYSET_FIELD_NUMBER;
      hash = (53 * hash) + getCategorySetList().hashCode();
    }
    if (getLabelSetCount() > 0) {
      hash = (37 * hash) + LABELSET_FIELD_NUMBER;
      hash = (53 * hash) + getLabelSetList().hashCode();
    }
    if (getLangSetCount() > 0) {
      hash = (37 * hash) + LANGSET_FIELD_NUMBER;
      hash = (53 * hash) + getLangSetList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mediaassetsdk.DescribeCategoriesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mediaassetsdk.DescribeCategoriesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mediaassetsdk.DescribeCategoriesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mediaassetsdk.DescribeCategoriesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mediaassetsdk.DescribeCategoriesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mediaassetsdk.DescribeCategoriesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mediaassetsdk.DescribeCategoriesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mediaassetsdk.DescribeCategoriesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mediaassetsdk.DescribeCategoriesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.mediaassetsdk.DescribeCategoriesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mediaassetsdk.DescribeCategoriesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mediaassetsdk.DescribeCategoriesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mediaassetsdk.DescribeCategoriesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code DescribeCategoriesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DescribeCategoriesResponse)
      com.mediaassetsdk.DescribeCategoriesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mediaassetsdk.MediaAsset.internal_static_DescribeCategoriesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mediaassetsdk.MediaAsset.internal_static_DescribeCategoriesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mediaassetsdk.DescribeCategoriesResponse.class, com.mediaassetsdk.DescribeCategoriesResponse.Builder.class);
    }

    // Construct using com.mediaassetsdk.DescribeCategoriesResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getErrorFieldBuilder();
        getCategorySetFieldBuilder();
        getLabelSetFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      requestID_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      if (errorBuilder_ == null) {
        error_ = null;
      } else {
        errorBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (categorySetBuilder_ == null) {
        categorySet_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        categorySetBuilder_.clear();
      }
      if (labelSetBuilder_ == null) {
        labelSet_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        labelSetBuilder_.clear();
      }
      langSet_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mediaassetsdk.MediaAsset.internal_static_DescribeCategoriesResponse_descriptor;
    }

    @java.lang.Override
    public com.mediaassetsdk.DescribeCategoriesResponse getDefaultInstanceForType() {
      return com.mediaassetsdk.DescribeCategoriesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.mediaassetsdk.DescribeCategoriesResponse build() {
      com.mediaassetsdk.DescribeCategoriesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mediaassetsdk.DescribeCategoriesResponse buildPartial() {
      com.mediaassetsdk.DescribeCategoriesResponse result = new com.mediaassetsdk.DescribeCategoriesResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.requestID_ = requestID_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        if (errorBuilder_ == null) {
          result.error_ = error_;
        } else {
          result.error_ = errorBuilder_.build();
        }
        to_bitField0_ |= 0x00000002;
      }
      if (categorySetBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          categorySet_ = java.util.Collections.unmodifiableList(categorySet_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.categorySet_ = categorySet_;
      } else {
        result.categorySet_ = categorySetBuilder_.build();
      }
      if (labelSetBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          labelSet_ = java.util.Collections.unmodifiableList(labelSet_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.labelSet_ = labelSet_;
      } else {
        result.labelSet_ = labelSetBuilder_.build();
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        langSet_ = langSet_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.langSet_ = langSet_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mediaassetsdk.DescribeCategoriesResponse) {
        return mergeFrom((com.mediaassetsdk.DescribeCategoriesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mediaassetsdk.DescribeCategoriesResponse other) {
      if (other == com.mediaassetsdk.DescribeCategoriesResponse.getDefaultInstance()) return this;
      if (other.hasRequestID()) {
        bitField0_ |= 0x00000001;
        requestID_ = other.requestID_;
        onChanged();
      }
      if (other.hasError()) {
        mergeError(other.getError());
      }
      if (categorySetBuilder_ == null) {
        if (!other.categorySet_.isEmpty()) {
          if (categorySet_.isEmpty()) {
            categorySet_ = other.categorySet_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureCategorySetIsMutable();
            categorySet_.addAll(other.categorySet_);
          }
          onChanged();
        }
      } else {
        if (!other.categorySet_.isEmpty()) {
          if (categorySetBuilder_.isEmpty()) {
            categorySetBuilder_.dispose();
            categorySetBuilder_ = null;
            categorySet_ = other.categorySet_;
            bitField0_ = (bitField0_ & ~0x00000004);
            categorySetBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCategorySetFieldBuilder() : null;
          } else {
            categorySetBuilder_.addAllMessages(other.categorySet_);
          }
        }
      }
      if (labelSetBuilder_ == null) {
        if (!other.labelSet_.isEmpty()) {
          if (labelSet_.isEmpty()) {
            labelSet_ = other.labelSet_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureLabelSetIsMutable();
            labelSet_.addAll(other.labelSet_);
          }
          onChanged();
        }
      } else {
        if (!other.labelSet_.isEmpty()) {
          if (labelSetBuilder_.isEmpty()) {
            labelSetBuilder_.dispose();
            labelSetBuilder_ = null;
            labelSet_ = other.labelSet_;
            bitField0_ = (bitField0_ & ~0x00000008);
            labelSetBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getLabelSetFieldBuilder() : null;
          } else {
            labelSetBuilder_.addAllMessages(other.labelSet_);
          }
        }
      }
      if (!other.langSet_.isEmpty()) {
        if (langSet_.isEmpty()) {
          langSet_ = other.langSet_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensureLangSetIsMutable();
          langSet_.addAll(other.langSet_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.mediaassetsdk.DescribeCategoriesResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.mediaassetsdk.DescribeCategoriesResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object requestID_ = "";
    /**
     * <code>optional string RequestID = 1;</code>
     * @return Whether the requestID field is set.
     */
    public boolean hasRequestID() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string RequestID = 1;</code>
     * @return The requestID.
     */
    public java.lang.String getRequestID() {
      java.lang.Object ref = requestID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string RequestID = 1;</code>
     * @return The bytes for requestID.
     */
    public com.google.protobuf.ByteString
        getRequestIDBytes() {
      java.lang.Object ref = requestID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string RequestID = 1;</code>
     * @param value The requestID to set.
     * @return This builder for chaining.
     */
    public Builder setRequestID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      requestID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string RequestID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestID() {
      bitField0_ = (bitField0_ & ~0x00000001);
      requestID_ = getDefaultInstance().getRequestID();
      onChanged();
      return this;
    }
    /**
     * <code>optional string RequestID = 1;</code>
     * @param value The bytes for requestID to set.
     * @return This builder for chaining.
     */
    public Builder setRequestIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      requestID_ = value;
      onChanged();
      return this;
    }

    private com.mediaassetsdk.Error error_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mediaassetsdk.Error, com.mediaassetsdk.Error.Builder, com.mediaassetsdk.ErrorOrBuilder> errorBuilder_;
    /**
     * <code>optional .Error Error = 2;</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .Error Error = 2;</code>
     * @return The error.
     */
    public com.mediaassetsdk.Error getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? com.mediaassetsdk.Error.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .Error Error = 2;</code>
     */
    public Builder setError(com.mediaassetsdk.Error value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .Error Error = 2;</code>
     */
    public Builder setError(
        com.mediaassetsdk.Error.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .Error Error = 2;</code>
     */
    public Builder mergeError(com.mediaassetsdk.Error value) {
      if (errorBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
            error_ != null &&
            error_ != com.mediaassetsdk.Error.getDefaultInstance()) {
          error_ =
            com.mediaassetsdk.Error.newBuilder(error_).mergeFrom(value).buildPartial();
        } else {
          error_ = value;
        }
        onChanged();
      } else {
        errorBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .Error Error = 2;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        error_ = null;
        onChanged();
      } else {
        errorBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>optional .Error Error = 2;</code>
     */
    public com.mediaassetsdk.Error.Builder getErrorBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .Error Error = 2;</code>
     */
    public com.mediaassetsdk.ErrorOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            com.mediaassetsdk.Error.getDefaultInstance() : error_;
      }
    }
    /**
     * <code>optional .Error Error = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mediaassetsdk.Error, com.mediaassetsdk.Error.Builder, com.mediaassetsdk.ErrorOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mediaassetsdk.Error, com.mediaassetsdk.Error.Builder, com.mediaassetsdk.ErrorOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }

    private java.util.List<com.mediaassetsdk.Category> categorySet_ =
      java.util.Collections.emptyList();
    private void ensureCategorySetIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        categorySet_ = new java.util.ArrayList<com.mediaassetsdk.Category>(categorySet_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.mediaassetsdk.Category, com.mediaassetsdk.Category.Builder, com.mediaassetsdk.CategoryOrBuilder> categorySetBuilder_;

    /**
     * <code>repeated .Category CategorySet = 3;</code>
     */
    public java.util.List<com.mediaassetsdk.Category> getCategorySetList() {
      if (categorySetBuilder_ == null) {
        return java.util.Collections.unmodifiableList(categorySet_);
      } else {
        return categorySetBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Category CategorySet = 3;</code>
     */
    public int getCategorySetCount() {
      if (categorySetBuilder_ == null) {
        return categorySet_.size();
      } else {
        return categorySetBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Category CategorySet = 3;</code>
     */
    public com.mediaassetsdk.Category getCategorySet(int index) {
      if (categorySetBuilder_ == null) {
        return categorySet_.get(index);
      } else {
        return categorySetBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Category CategorySet = 3;</code>
     */
    public Builder setCategorySet(
        int index, com.mediaassetsdk.Category value) {
      if (categorySetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCategorySetIsMutable();
        categorySet_.set(index, value);
        onChanged();
      } else {
        categorySetBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Category CategorySet = 3;</code>
     */
    public Builder setCategorySet(
        int index, com.mediaassetsdk.Category.Builder builderForValue) {
      if (categorySetBuilder_ == null) {
        ensureCategorySetIsMutable();
        categorySet_.set(index, builderForValue.build());
        onChanged();
      } else {
        categorySetBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Category CategorySet = 3;</code>
     */
    public Builder addCategorySet(com.mediaassetsdk.Category value) {
      if (categorySetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCategorySetIsMutable();
        categorySet_.add(value);
        onChanged();
      } else {
        categorySetBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Category CategorySet = 3;</code>
     */
    public Builder addCategorySet(
        int index, com.mediaassetsdk.Category value) {
      if (categorySetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCategorySetIsMutable();
        categorySet_.add(index, value);
        onChanged();
      } else {
        categorySetBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Category CategorySet = 3;</code>
     */
    public Builder addCategorySet(
        com.mediaassetsdk.Category.Builder builderForValue) {
      if (categorySetBuilder_ == null) {
        ensureCategorySetIsMutable();
        categorySet_.add(builderForValue.build());
        onChanged();
      } else {
        categorySetBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Category CategorySet = 3;</code>
     */
    public Builder addCategorySet(
        int index, com.mediaassetsdk.Category.Builder builderForValue) {
      if (categorySetBuilder_ == null) {
        ensureCategorySetIsMutable();
        categorySet_.add(index, builderForValue.build());
        onChanged();
      } else {
        categorySetBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Category CategorySet = 3;</code>
     */
    public Builder addAllCategorySet(
        java.lang.Iterable<? extends com.mediaassetsdk.Category> values) {
      if (categorySetBuilder_ == null) {
        ensureCategorySetIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, categorySet_);
        onChanged();
      } else {
        categorySetBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Category CategorySet = 3;</code>
     */
    public Builder clearCategorySet() {
      if (categorySetBuilder_ == null) {
        categorySet_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        categorySetBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Category CategorySet = 3;</code>
     */
    public Builder removeCategorySet(int index) {
      if (categorySetBuilder_ == null) {
        ensureCategorySetIsMutable();
        categorySet_.remove(index);
        onChanged();
      } else {
        categorySetBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Category CategorySet = 3;</code>
     */
    public com.mediaassetsdk.Category.Builder getCategorySetBuilder(
        int index) {
      return getCategorySetFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Category CategorySet = 3;</code>
     */
    public com.mediaassetsdk.CategoryOrBuilder getCategorySetOrBuilder(
        int index) {
      if (categorySetBuilder_ == null) {
        return categorySet_.get(index);  } else {
        return categorySetBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Category CategorySet = 3;</code>
     */
    public java.util.List<? extends com.mediaassetsdk.CategoryOrBuilder> 
         getCategorySetOrBuilderList() {
      if (categorySetBuilder_ != null) {
        return categorySetBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(categorySet_);
      }
    }
    /**
     * <code>repeated .Category CategorySet = 3;</code>
     */
    public com.mediaassetsdk.Category.Builder addCategorySetBuilder() {
      return getCategorySetFieldBuilder().addBuilder(
          com.mediaassetsdk.Category.getDefaultInstance());
    }
    /**
     * <code>repeated .Category CategorySet = 3;</code>
     */
    public com.mediaassetsdk.Category.Builder addCategorySetBuilder(
        int index) {
      return getCategorySetFieldBuilder().addBuilder(
          index, com.mediaassetsdk.Category.getDefaultInstance());
    }
    /**
     * <code>repeated .Category CategorySet = 3;</code>
     */
    public java.util.List<com.mediaassetsdk.Category.Builder> 
         getCategorySetBuilderList() {
      return getCategorySetFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.mediaassetsdk.Category, com.mediaassetsdk.Category.Builder, com.mediaassetsdk.CategoryOrBuilder> 
        getCategorySetFieldBuilder() {
      if (categorySetBuilder_ == null) {
        categorySetBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.mediaassetsdk.Category, com.mediaassetsdk.Category.Builder, com.mediaassetsdk.CategoryOrBuilder>(
                categorySet_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        categorySet_ = null;
      }
      return categorySetBuilder_;
    }

    private java.util.List<com.mediaassetsdk.Label> labelSet_ =
      java.util.Collections.emptyList();
    private void ensureLabelSetIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        labelSet_ = new java.util.ArrayList<com.mediaassetsdk.Label>(labelSet_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.mediaassetsdk.Label, com.mediaassetsdk.Label.Builder, com.mediaassetsdk.LabelOrBuilder> labelSetBuilder_;

    /**
     * <code>repeated .Label LabelSet = 4;</code>
     */
    public java.util.List<com.mediaassetsdk.Label> getLabelSetList() {
      if (labelSetBuilder_ == null) {
        return java.util.Collections.unmodifiableList(labelSet_);
      } else {
        return labelSetBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Label LabelSet = 4;</code>
     */
    public int getLabelSetCount() {
      if (labelSetBuilder_ == null) {
        return labelSet_.size();
      } else {
        return labelSetBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Label LabelSet = 4;</code>
     */
    public com.mediaassetsdk.Label getLabelSet(int index) {
      if (labelSetBuilder_ == null) {
        return labelSet_.get(index);
      } else {
        return labelSetBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Label LabelSet = 4;</code>
     */
    public Builder setLabelSet(
        int index, com.mediaassetsdk.Label value) {
      if (labelSetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLabelSetIsMutable();
        labelSet_.set(index, value);
        onChanged();
      } else {
        labelSetBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Label LabelSet = 4;</code>
     */
    public Builder setLabelSet(
        int index, com.mediaassetsdk.Label.Builder builderForValue) {
      if (labelSetBuilder_ == null) {
        ensureLabelSetIsMutable();
        labelSet_.set(index, builderForValue.build());
        onChanged();
      } else {
        labelSetBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Label LabelSet = 4;</code>
     */
    public Builder addLabelSet(com.mediaassetsdk.Label value) {
      if (labelSetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLabelSetIsMutable();
        labelSet_.add(value);
        onChanged();
      } else {
        labelSetBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Label LabelSet = 4;</code>
     */
    public Builder addLabelSet(
        int index, com.mediaassetsdk.Label value) {
      if (labelSetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLabelSetIsMutable();
        labelSet_.add(index, value);
        onChanged();
      } else {
        labelSetBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Label LabelSet = 4;</code>
     */
    public Builder addLabelSet(
        com.mediaassetsdk.Label.Builder builderForValue) {
      if (labelSetBuilder_ == null) {
        ensureLabelSetIsMutable();
        labelSet_.add(builderForValue.build());
        onChanged();
      } else {
        labelSetBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Label LabelSet = 4;</code>
     */
    public Builder addLabelSet(
        int index, com.mediaassetsdk.Label.Builder builderForValue) {
      if (labelSetBuilder_ == null) {
        ensureLabelSetIsMutable();
        labelSet_.add(index, builderForValue.build());
        onChanged();
      } else {
        labelSetBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Label LabelSet = 4;</code>
     */
    public Builder addAllLabelSet(
        java.lang.Iterable<? extends com.mediaassetsdk.Label> values) {
      if (labelSetBuilder_ == null) {
        ensureLabelSetIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, labelSet_);
        onChanged();
      } else {
        labelSetBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Label LabelSet = 4;</code>
     */
    public Builder clearLabelSet() {
      if (labelSetBuilder_ == null) {
        labelSet_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        labelSetBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Label LabelSet = 4;</code>
     */
    public Builder removeLabelSet(int index) {
      if (labelSetBuilder_ == null) {
        ensureLabelSetIsMutable();
        labelSet_.remove(index);
        onChanged();
      } else {
        labelSetBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Label LabelSet = 4;</code>
     */
    public com.mediaassetsdk.Label.Builder getLabelSetBuilder(
        int index) {
      return getLabelSetFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Label LabelSet = 4;</code>
     */
    public com.mediaassetsdk.LabelOrBuilder getLabelSetOrBuilder(
        int index) {
      if (labelSetBuilder_ == null) {
        return labelSet_.get(index);  } else {
        return labelSetBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Label LabelSet = 4;</code>
     */
    public java.util.List<? extends com.mediaassetsdk.LabelOrBuilder> 
         getLabelSetOrBuilderList() {
      if (labelSetBuilder_ != null) {
        return labelSetBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(labelSet_);
      }
    }
    /**
     * <code>repeated .Label LabelSet = 4;</code>
     */
    public com.mediaassetsdk.Label.Builder addLabelSetBuilder() {
      return getLabelSetFieldBuilder().addBuilder(
          com.mediaassetsdk.Label.getDefaultInstance());
    }
    /**
     * <code>repeated .Label LabelSet = 4;</code>
     */
    public com.mediaassetsdk.Label.Builder addLabelSetBuilder(
        int index) {
      return getLabelSetFieldBuilder().addBuilder(
          index, com.mediaassetsdk.Label.getDefaultInstance());
    }
    /**
     * <code>repeated .Label LabelSet = 4;</code>
     */
    public java.util.List<com.mediaassetsdk.Label.Builder> 
         getLabelSetBuilderList() {
      return getLabelSetFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.mediaassetsdk.Label, com.mediaassetsdk.Label.Builder, com.mediaassetsdk.LabelOrBuilder> 
        getLabelSetFieldBuilder() {
      if (labelSetBuilder_ == null) {
        labelSetBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.mediaassetsdk.Label, com.mediaassetsdk.Label.Builder, com.mediaassetsdk.LabelOrBuilder>(
                labelSet_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        labelSet_ = null;
      }
      return labelSetBuilder_;
    }

    private com.google.protobuf.LazyStringList langSet_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureLangSetIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        langSet_ = new com.google.protobuf.LazyStringArrayList(langSet_);
        bitField0_ |= 0x00000010;
       }
    }
    /**
     * <code>repeated string LangSet = 5;</code>
     * @return A list containing the langSet.
     */
    public com.google.protobuf.ProtocolStringList
        getLangSetList() {
      return langSet_.getUnmodifiableView();
    }
    /**
     * <code>repeated string LangSet = 5;</code>
     * @return The count of langSet.
     */
    public int getLangSetCount() {
      return langSet_.size();
    }
    /**
     * <code>repeated string LangSet = 5;</code>
     * @param index The index of the element to return.
     * @return The langSet at the given index.
     */
    public java.lang.String getLangSet(int index) {
      return langSet_.get(index);
    }
    /**
     * <code>repeated string LangSet = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the langSet at the given index.
     */
    public com.google.protobuf.ByteString
        getLangSetBytes(int index) {
      return langSet_.getByteString(index);
    }
    /**
     * <code>repeated string LangSet = 5;</code>
     * @param index The index to set the value at.
     * @param value The langSet to set.
     * @return This builder for chaining.
     */
    public Builder setLangSet(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureLangSetIsMutable();
      langSet_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string LangSet = 5;</code>
     * @param value The langSet to add.
     * @return This builder for chaining.
     */
    public Builder addLangSet(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureLangSetIsMutable();
      langSet_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string LangSet = 5;</code>
     * @param values The langSet to add.
     * @return This builder for chaining.
     */
    public Builder addAllLangSet(
        java.lang.Iterable<java.lang.String> values) {
      ensureLangSetIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, langSet_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string LangSet = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLangSet() {
      langSet_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string LangSet = 5;</code>
     * @param value The bytes of the langSet to add.
     * @return This builder for chaining.
     */
    public Builder addLangSetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureLangSetIsMutable();
      langSet_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:DescribeCategoriesResponse)
  }

  // @@protoc_insertion_point(class_scope:DescribeCategoriesResponse)
  private static final com.mediaassetsdk.DescribeCategoriesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mediaassetsdk.DescribeCategoriesResponse();
  }

  public static com.mediaassetsdk.DescribeCategoriesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DescribeCategoriesResponse>
      PARSER = new com.google.protobuf.AbstractParser<DescribeCategoriesResponse>() {
    @java.lang.Override
    public DescribeCategoriesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DescribeCategoriesResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DescribeCategoriesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DescribeCategoriesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mediaassetsdk.DescribeCategoriesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

