// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MediaAsset.proto

package com.mediaassetsdk;

/**
 * Protobuf type {@code MediaInfo}
 */
public final class MediaInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MediaInfo)
    MediaInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MediaInfo.newBuilder() to construct.
  private MediaInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MediaInfo() {
    name_ = "";
    format_ = "";
    mediaType_ = "";
    mediaTag_ = "";
    mediaSecondTag_ = "";
    mediaLang_ = "";
    downLoadURL_ = "";
    status_ = "";
    failedReason_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MediaInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MediaInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            mediaID_ = input.readUInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000002;
            name_ = s;
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            duration_ = input.readUInt32();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            size_ = input.readUInt32();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000010;
            width_ = input.readUInt32();
            break;
          }
          case 48: {
            bitField0_ |= 0x00000020;
            height_ = input.readUInt32();
            break;
          }
          case 56: {
            bitField0_ |= 0x00000040;
            fPS_ = input.readUInt32();
            break;
          }
          case 64: {
            bitField0_ |= 0x00000080;
            bitRate_ = input.readUInt32();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000100;
            format_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000200;
            mediaType_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000400;
            mediaTag_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000800;
            mediaSecondTag_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00001000;
            mediaLang_ = s;
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00002000;
            downLoadURL_ = s;
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00004000;
            status_ = s;
            break;
          }
          case 130: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00008000;
            failedReason_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mediaassetsdk.MediaAsset.internal_static_MediaInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mediaassetsdk.MediaAsset.internal_static_MediaInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mediaassetsdk.MediaInfo.class, com.mediaassetsdk.MediaInfo.Builder.class);
  }

  private int bitField0_;
  public static final int MEDIAID_FIELD_NUMBER = 1;
  private long mediaID_;
  /**
   * <code>optional uint64 MediaID = 1;</code>
   * @return Whether the mediaID field is set.
   */
  @java.lang.Override
  public boolean hasMediaID() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional uint64 MediaID = 1;</code>
   * @return The mediaID.
   */
  @java.lang.Override
  public long getMediaID() {
    return mediaID_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string Name = 2;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string Name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string Name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DURATION_FIELD_NUMBER = 3;
  private int duration_;
  /**
   * <code>optional uint32 Duration = 3;</code>
   * @return Whether the duration field is set.
   */
  @java.lang.Override
  public boolean hasDuration() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional uint32 Duration = 3;</code>
   * @return The duration.
   */
  @java.lang.Override
  public int getDuration() {
    return duration_;
  }

  public static final int SIZE_FIELD_NUMBER = 4;
  private int size_;
  /**
   * <code>optional uint32 Size = 4;</code>
   * @return Whether the size field is set.
   */
  @java.lang.Override
  public boolean hasSize() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional uint32 Size = 4;</code>
   * @return The size.
   */
  @java.lang.Override
  public int getSize() {
    return size_;
  }

  public static final int WIDTH_FIELD_NUMBER = 5;
  private int width_;
  /**
   * <code>optional uint32 Width = 5;</code>
   * @return Whether the width field is set.
   */
  @java.lang.Override
  public boolean hasWidth() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional uint32 Width = 5;</code>
   * @return The width.
   */
  @java.lang.Override
  public int getWidth() {
    return width_;
  }

  public static final int HEIGHT_FIELD_NUMBER = 6;
  private int height_;
  /**
   * <code>optional uint32 Height = 6;</code>
   * @return Whether the height field is set.
   */
  @java.lang.Override
  public boolean hasHeight() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional uint32 Height = 6;</code>
   * @return The height.
   */
  @java.lang.Override
  public int getHeight() {
    return height_;
  }

  public static final int FPS_FIELD_NUMBER = 7;
  private int fPS_;
  /**
   * <code>optional uint32 FPS = 7;</code>
   * @return Whether the fPS field is set.
   */
  @java.lang.Override
  public boolean hasFPS() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional uint32 FPS = 7;</code>
   * @return The fPS.
   */
  @java.lang.Override
  public int getFPS() {
    return fPS_;
  }

  public static final int BITRATE_FIELD_NUMBER = 8;
  private int bitRate_;
  /**
   * <code>optional uint32 BitRate = 8;</code>
   * @return Whether the bitRate field is set.
   */
  @java.lang.Override
  public boolean hasBitRate() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional uint32 BitRate = 8;</code>
   * @return The bitRate.
   */
  @java.lang.Override
  public int getBitRate() {
    return bitRate_;
  }

  public static final int FORMAT_FIELD_NUMBER = 9;
  private volatile java.lang.Object format_;
  /**
   * <code>optional string Format = 9;</code>
   * @return Whether the format field is set.
   */
  @java.lang.Override
  public boolean hasFormat() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <code>optional string Format = 9;</code>
   * @return The format.
   */
  @java.lang.Override
  public java.lang.String getFormat() {
    java.lang.Object ref = format_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      format_ = s;
      return s;
    }
  }
  /**
   * <code>optional string Format = 9;</code>
   * @return The bytes for format.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFormatBytes() {
    java.lang.Object ref = format_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      format_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MEDIATYPE_FIELD_NUMBER = 10;
  private volatile java.lang.Object mediaType_;
  /**
   * <code>optional string MediaType = 10;</code>
   * @return Whether the mediaType field is set.
   */
  @java.lang.Override
  public boolean hasMediaType() {
    return ((bitField0_ & 0x00000200) != 0);
  }
  /**
   * <code>optional string MediaType = 10;</code>
   * @return The mediaType.
   */
  @java.lang.Override
  public java.lang.String getMediaType() {
    java.lang.Object ref = mediaType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mediaType_ = s;
      return s;
    }
  }
  /**
   * <code>optional string MediaType = 10;</code>
   * @return The bytes for mediaType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMediaTypeBytes() {
    java.lang.Object ref = mediaType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mediaType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MEDIATAG_FIELD_NUMBER = 11;
  private volatile java.lang.Object mediaTag_;
  /**
   * <code>optional string MediaTag = 11;</code>
   * @return Whether the mediaTag field is set.
   */
  @java.lang.Override
  public boolean hasMediaTag() {
    return ((bitField0_ & 0x00000400) != 0);
  }
  /**
   * <code>optional string MediaTag = 11;</code>
   * @return The mediaTag.
   */
  @java.lang.Override
  public java.lang.String getMediaTag() {
    java.lang.Object ref = mediaTag_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mediaTag_ = s;
      return s;
    }
  }
  /**
   * <code>optional string MediaTag = 11;</code>
   * @return The bytes for mediaTag.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMediaTagBytes() {
    java.lang.Object ref = mediaTag_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mediaTag_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MEDIASECONDTAG_FIELD_NUMBER = 12;
  private volatile java.lang.Object mediaSecondTag_;
  /**
   * <code>optional string MediaSecondTag = 12;</code>
   * @return Whether the mediaSecondTag field is set.
   */
  @java.lang.Override
  public boolean hasMediaSecondTag() {
    return ((bitField0_ & 0x00000800) != 0);
  }
  /**
   * <code>optional string MediaSecondTag = 12;</code>
   * @return The mediaSecondTag.
   */
  @java.lang.Override
  public java.lang.String getMediaSecondTag() {
    java.lang.Object ref = mediaSecondTag_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mediaSecondTag_ = s;
      return s;
    }
  }
  /**
   * <code>optional string MediaSecondTag = 12;</code>
   * @return The bytes for mediaSecondTag.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMediaSecondTagBytes() {
    java.lang.Object ref = mediaSecondTag_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mediaSecondTag_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MEDIALANG_FIELD_NUMBER = 13;
  private volatile java.lang.Object mediaLang_;
  /**
   * <code>optional string MediaLang = 13;</code>
   * @return Whether the mediaLang field is set.
   */
  @java.lang.Override
  public boolean hasMediaLang() {
    return ((bitField0_ & 0x00001000) != 0);
  }
  /**
   * <code>optional string MediaLang = 13;</code>
   * @return The mediaLang.
   */
  @java.lang.Override
  public java.lang.String getMediaLang() {
    java.lang.Object ref = mediaLang_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mediaLang_ = s;
      return s;
    }
  }
  /**
   * <code>optional string MediaLang = 13;</code>
   * @return The bytes for mediaLang.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMediaLangBytes() {
    java.lang.Object ref = mediaLang_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mediaLang_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DOWNLOADURL_FIELD_NUMBER = 14;
  private volatile java.lang.Object downLoadURL_;
  /**
   * <code>optional string DownLoadURL = 14;</code>
   * @return Whether the downLoadURL field is set.
   */
  @java.lang.Override
  public boolean hasDownLoadURL() {
    return ((bitField0_ & 0x00002000) != 0);
  }
  /**
   * <code>optional string DownLoadURL = 14;</code>
   * @return The downLoadURL.
   */
  @java.lang.Override
  public java.lang.String getDownLoadURL() {
    java.lang.Object ref = downLoadURL_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      downLoadURL_ = s;
      return s;
    }
  }
  /**
   * <code>optional string DownLoadURL = 14;</code>
   * @return The bytes for downLoadURL.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDownLoadURLBytes() {
    java.lang.Object ref = downLoadURL_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      downLoadURL_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 15;
  private volatile java.lang.Object status_;
  /**
   * <code>optional string Status = 15;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return ((bitField0_ & 0x00004000) != 0);
  }
  /**
   * <code>optional string Status = 15;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>optional string Status = 15;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FAILEDREASON_FIELD_NUMBER = 16;
  private volatile java.lang.Object failedReason_;
  /**
   * <code>optional string FailedReason = 16;</code>
   * @return Whether the failedReason field is set.
   */
  @java.lang.Override
  public boolean hasFailedReason() {
    return ((bitField0_ & 0x00008000) != 0);
  }
  /**
   * <code>optional string FailedReason = 16;</code>
   * @return The failedReason.
   */
  @java.lang.Override
  public java.lang.String getFailedReason() {
    java.lang.Object ref = failedReason_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      failedReason_ = s;
      return s;
    }
  }
  /**
   * <code>optional string FailedReason = 16;</code>
   * @return The bytes for failedReason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFailedReasonBytes() {
    java.lang.Object ref = failedReason_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      failedReason_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeUInt64(1, mediaID_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeUInt32(3, duration_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeUInt32(4, size_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeUInt32(5, width_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeUInt32(6, height_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeUInt32(7, fPS_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeUInt32(8, bitRate_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, format_);
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, mediaType_);
    }
    if (((bitField0_ & 0x00000400) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, mediaTag_);
    }
    if (((bitField0_ & 0x00000800) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, mediaSecondTag_);
    }
    if (((bitField0_ & 0x00001000) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, mediaLang_);
    }
    if (((bitField0_ & 0x00002000) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, downLoadURL_);
    }
    if (((bitField0_ & 0x00004000) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, status_);
    }
    if (((bitField0_ & 0x00008000) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, failedReason_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, mediaID_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, duration_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, size_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, width_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, height_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(7, fPS_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(8, bitRate_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, format_);
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, mediaType_);
    }
    if (((bitField0_ & 0x00000400) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, mediaTag_);
    }
    if (((bitField0_ & 0x00000800) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, mediaSecondTag_);
    }
    if (((bitField0_ & 0x00001000) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, mediaLang_);
    }
    if (((bitField0_ & 0x00002000) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, downLoadURL_);
    }
    if (((bitField0_ & 0x00004000) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, status_);
    }
    if (((bitField0_ & 0x00008000) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, failedReason_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mediaassetsdk.MediaInfo)) {
      return super.equals(obj);
    }
    com.mediaassetsdk.MediaInfo other = (com.mediaassetsdk.MediaInfo) obj;

    if (hasMediaID() != other.hasMediaID()) return false;
    if (hasMediaID()) {
      if (getMediaID()
          != other.getMediaID()) return false;
    }
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasDuration() != other.hasDuration()) return false;
    if (hasDuration()) {
      if (getDuration()
          != other.getDuration()) return false;
    }
    if (hasSize() != other.hasSize()) return false;
    if (hasSize()) {
      if (getSize()
          != other.getSize()) return false;
    }
    if (hasWidth() != other.hasWidth()) return false;
    if (hasWidth()) {
      if (getWidth()
          != other.getWidth()) return false;
    }
    if (hasHeight() != other.hasHeight()) return false;
    if (hasHeight()) {
      if (getHeight()
          != other.getHeight()) return false;
    }
    if (hasFPS() != other.hasFPS()) return false;
    if (hasFPS()) {
      if (getFPS()
          != other.getFPS()) return false;
    }
    if (hasBitRate() != other.hasBitRate()) return false;
    if (hasBitRate()) {
      if (getBitRate()
          != other.getBitRate()) return false;
    }
    if (hasFormat() != other.hasFormat()) return false;
    if (hasFormat()) {
      if (!getFormat()
          .equals(other.getFormat())) return false;
    }
    if (hasMediaType() != other.hasMediaType()) return false;
    if (hasMediaType()) {
      if (!getMediaType()
          .equals(other.getMediaType())) return false;
    }
    if (hasMediaTag() != other.hasMediaTag()) return false;
    if (hasMediaTag()) {
      if (!getMediaTag()
          .equals(other.getMediaTag())) return false;
    }
    if (hasMediaSecondTag() != other.hasMediaSecondTag()) return false;
    if (hasMediaSecondTag()) {
      if (!getMediaSecondTag()
          .equals(other.getMediaSecondTag())) return false;
    }
    if (hasMediaLang() != other.hasMediaLang()) return false;
    if (hasMediaLang()) {
      if (!getMediaLang()
          .equals(other.getMediaLang())) return false;
    }
    if (hasDownLoadURL() != other.hasDownLoadURL()) return false;
    if (hasDownLoadURL()) {
      if (!getDownLoadURL()
          .equals(other.getDownLoadURL())) return false;
    }
    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (hasFailedReason() != other.hasFailedReason()) return false;
    if (hasFailedReason()) {
      if (!getFailedReason()
          .equals(other.getFailedReason())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMediaID()) {
      hash = (37 * hash) + MEDIAID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMediaID());
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasDuration()) {
      hash = (37 * hash) + DURATION_FIELD_NUMBER;
      hash = (53 * hash) + getDuration();
    }
    if (hasSize()) {
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize();
    }
    if (hasWidth()) {
      hash = (37 * hash) + WIDTH_FIELD_NUMBER;
      hash = (53 * hash) + getWidth();
    }
    if (hasHeight()) {
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getHeight();
    }
    if (hasFPS()) {
      hash = (37 * hash) + FPS_FIELD_NUMBER;
      hash = (53 * hash) + getFPS();
    }
    if (hasBitRate()) {
      hash = (37 * hash) + BITRATE_FIELD_NUMBER;
      hash = (53 * hash) + getBitRate();
    }
    if (hasFormat()) {
      hash = (37 * hash) + FORMAT_FIELD_NUMBER;
      hash = (53 * hash) + getFormat().hashCode();
    }
    if (hasMediaType()) {
      hash = (37 * hash) + MEDIATYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMediaType().hashCode();
    }
    if (hasMediaTag()) {
      hash = (37 * hash) + MEDIATAG_FIELD_NUMBER;
      hash = (53 * hash) + getMediaTag().hashCode();
    }
    if (hasMediaSecondTag()) {
      hash = (37 * hash) + MEDIASECONDTAG_FIELD_NUMBER;
      hash = (53 * hash) + getMediaSecondTag().hashCode();
    }
    if (hasMediaLang()) {
      hash = (37 * hash) + MEDIALANG_FIELD_NUMBER;
      hash = (53 * hash) + getMediaLang().hashCode();
    }
    if (hasDownLoadURL()) {
      hash = (37 * hash) + DOWNLOADURL_FIELD_NUMBER;
      hash = (53 * hash) + getDownLoadURL().hashCode();
    }
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    if (hasFailedReason()) {
      hash = (37 * hash) + FAILEDREASON_FIELD_NUMBER;
      hash = (53 * hash) + getFailedReason().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mediaassetsdk.MediaInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mediaassetsdk.MediaInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mediaassetsdk.MediaInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mediaassetsdk.MediaInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mediaassetsdk.MediaInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mediaassetsdk.MediaInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mediaassetsdk.MediaInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mediaassetsdk.MediaInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mediaassetsdk.MediaInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.mediaassetsdk.MediaInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mediaassetsdk.MediaInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mediaassetsdk.MediaInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mediaassetsdk.MediaInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MediaInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MediaInfo)
      com.mediaassetsdk.MediaInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mediaassetsdk.MediaAsset.internal_static_MediaInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mediaassetsdk.MediaAsset.internal_static_MediaInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mediaassetsdk.MediaInfo.class, com.mediaassetsdk.MediaInfo.Builder.class);
    }

    // Construct using com.mediaassetsdk.MediaInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      mediaID_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      duration_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      size_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      width_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      height_ = 0;
      bitField0_ = (bitField0_ & ~0x00000020);
      fPS_ = 0;
      bitField0_ = (bitField0_ & ~0x00000040);
      bitRate_ = 0;
      bitField0_ = (bitField0_ & ~0x00000080);
      format_ = "";
      bitField0_ = (bitField0_ & ~0x00000100);
      mediaType_ = "";
      bitField0_ = (bitField0_ & ~0x00000200);
      mediaTag_ = "";
      bitField0_ = (bitField0_ & ~0x00000400);
      mediaSecondTag_ = "";
      bitField0_ = (bitField0_ & ~0x00000800);
      mediaLang_ = "";
      bitField0_ = (bitField0_ & ~0x00001000);
      downLoadURL_ = "";
      bitField0_ = (bitField0_ & ~0x00002000);
      status_ = "";
      bitField0_ = (bitField0_ & ~0x00004000);
      failedReason_ = "";
      bitField0_ = (bitField0_ & ~0x00008000);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mediaassetsdk.MediaAsset.internal_static_MediaInfo_descriptor;
    }

    @java.lang.Override
    public com.mediaassetsdk.MediaInfo getDefaultInstanceForType() {
      return com.mediaassetsdk.MediaInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.mediaassetsdk.MediaInfo build() {
      com.mediaassetsdk.MediaInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mediaassetsdk.MediaInfo buildPartial() {
      com.mediaassetsdk.MediaInfo result = new com.mediaassetsdk.MediaInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.mediaID_ = mediaID_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.duration_ = duration_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.size_ = size_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.width_ = width_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.height_ = height_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.fPS_ = fPS_;
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.bitRate_ = bitRate_;
        to_bitField0_ |= 0x00000080;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        to_bitField0_ |= 0x00000100;
      }
      result.format_ = format_;
      if (((from_bitField0_ & 0x00000200) != 0)) {
        to_bitField0_ |= 0x00000200;
      }
      result.mediaType_ = mediaType_;
      if (((from_bitField0_ & 0x00000400) != 0)) {
        to_bitField0_ |= 0x00000400;
      }
      result.mediaTag_ = mediaTag_;
      if (((from_bitField0_ & 0x00000800) != 0)) {
        to_bitField0_ |= 0x00000800;
      }
      result.mediaSecondTag_ = mediaSecondTag_;
      if (((from_bitField0_ & 0x00001000) != 0)) {
        to_bitField0_ |= 0x00001000;
      }
      result.mediaLang_ = mediaLang_;
      if (((from_bitField0_ & 0x00002000) != 0)) {
        to_bitField0_ |= 0x00002000;
      }
      result.downLoadURL_ = downLoadURL_;
      if (((from_bitField0_ & 0x00004000) != 0)) {
        to_bitField0_ |= 0x00004000;
      }
      result.status_ = status_;
      if (((from_bitField0_ & 0x00008000) != 0)) {
        to_bitField0_ |= 0x00008000;
      }
      result.failedReason_ = failedReason_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mediaassetsdk.MediaInfo) {
        return mergeFrom((com.mediaassetsdk.MediaInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mediaassetsdk.MediaInfo other) {
      if (other == com.mediaassetsdk.MediaInfo.getDefaultInstance()) return this;
      if (other.hasMediaID()) {
        setMediaID(other.getMediaID());
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000002;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasDuration()) {
        setDuration(other.getDuration());
      }
      if (other.hasSize()) {
        setSize(other.getSize());
      }
      if (other.hasWidth()) {
        setWidth(other.getWidth());
      }
      if (other.hasHeight()) {
        setHeight(other.getHeight());
      }
      if (other.hasFPS()) {
        setFPS(other.getFPS());
      }
      if (other.hasBitRate()) {
        setBitRate(other.getBitRate());
      }
      if (other.hasFormat()) {
        bitField0_ |= 0x00000100;
        format_ = other.format_;
        onChanged();
      }
      if (other.hasMediaType()) {
        bitField0_ |= 0x00000200;
        mediaType_ = other.mediaType_;
        onChanged();
      }
      if (other.hasMediaTag()) {
        bitField0_ |= 0x00000400;
        mediaTag_ = other.mediaTag_;
        onChanged();
      }
      if (other.hasMediaSecondTag()) {
        bitField0_ |= 0x00000800;
        mediaSecondTag_ = other.mediaSecondTag_;
        onChanged();
      }
      if (other.hasMediaLang()) {
        bitField0_ |= 0x00001000;
        mediaLang_ = other.mediaLang_;
        onChanged();
      }
      if (other.hasDownLoadURL()) {
        bitField0_ |= 0x00002000;
        downLoadURL_ = other.downLoadURL_;
        onChanged();
      }
      if (other.hasStatus()) {
        bitField0_ |= 0x00004000;
        status_ = other.status_;
        onChanged();
      }
      if (other.hasFailedReason()) {
        bitField0_ |= 0x00008000;
        failedReason_ = other.failedReason_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.mediaassetsdk.MediaInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.mediaassetsdk.MediaInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long mediaID_ ;
    /**
     * <code>optional uint64 MediaID = 1;</code>
     * @return Whether the mediaID field is set.
     */
    @java.lang.Override
    public boolean hasMediaID() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint64 MediaID = 1;</code>
     * @return The mediaID.
     */
    @java.lang.Override
    public long getMediaID() {
      return mediaID_;
    }
    /**
     * <code>optional uint64 MediaID = 1;</code>
     * @param value The mediaID to set.
     * @return This builder for chaining.
     */
    public Builder setMediaID(long value) {
      bitField0_ |= 0x00000001;
      mediaID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 MediaID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMediaID() {
      bitField0_ = (bitField0_ & ~0x00000001);
      mediaID_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>optional string Name = 2;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string Name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string Name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string Name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string Name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string Name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }

    private int duration_ ;
    /**
     * <code>optional uint32 Duration = 3;</code>
     * @return Whether the duration field is set.
     */
    @java.lang.Override
    public boolean hasDuration() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint32 Duration = 3;</code>
     * @return The duration.
     */
    @java.lang.Override
    public int getDuration() {
      return duration_;
    }
    /**
     * <code>optional uint32 Duration = 3;</code>
     * @param value The duration to set.
     * @return This builder for chaining.
     */
    public Builder setDuration(int value) {
      bitField0_ |= 0x00000004;
      duration_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 Duration = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDuration() {
      bitField0_ = (bitField0_ & ~0x00000004);
      duration_ = 0;
      onChanged();
      return this;
    }

    private int size_ ;
    /**
     * <code>optional uint32 Size = 4;</code>
     * @return Whether the size field is set.
     */
    @java.lang.Override
    public boolean hasSize() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint32 Size = 4;</code>
     * @return The size.
     */
    @java.lang.Override
    public int getSize() {
      return size_;
    }
    /**
     * <code>optional uint32 Size = 4;</code>
     * @param value The size to set.
     * @return This builder for chaining.
     */
    public Builder setSize(int value) {
      bitField0_ |= 0x00000008;
      size_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 Size = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSize() {
      bitField0_ = (bitField0_ & ~0x00000008);
      size_ = 0;
      onChanged();
      return this;
    }

    private int width_ ;
    /**
     * <code>optional uint32 Width = 5;</code>
     * @return Whether the width field is set.
     */
    @java.lang.Override
    public boolean hasWidth() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional uint32 Width = 5;</code>
     * @return The width.
     */
    @java.lang.Override
    public int getWidth() {
      return width_;
    }
    /**
     * <code>optional uint32 Width = 5;</code>
     * @param value The width to set.
     * @return This builder for chaining.
     */
    public Builder setWidth(int value) {
      bitField0_ |= 0x00000010;
      width_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 Width = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearWidth() {
      bitField0_ = (bitField0_ & ~0x00000010);
      width_ = 0;
      onChanged();
      return this;
    }

    private int height_ ;
    /**
     * <code>optional uint32 Height = 6;</code>
     * @return Whether the height field is set.
     */
    @java.lang.Override
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional uint32 Height = 6;</code>
     * @return The height.
     */
    @java.lang.Override
    public int getHeight() {
      return height_;
    }
    /**
     * <code>optional uint32 Height = 6;</code>
     * @param value The height to set.
     * @return This builder for chaining.
     */
    public Builder setHeight(int value) {
      bitField0_ |= 0x00000020;
      height_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 Height = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeight() {
      bitField0_ = (bitField0_ & ~0x00000020);
      height_ = 0;
      onChanged();
      return this;
    }

    private int fPS_ ;
    /**
     * <code>optional uint32 FPS = 7;</code>
     * @return Whether the fPS field is set.
     */
    @java.lang.Override
    public boolean hasFPS() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional uint32 FPS = 7;</code>
     * @return The fPS.
     */
    @java.lang.Override
    public int getFPS() {
      return fPS_;
    }
    /**
     * <code>optional uint32 FPS = 7;</code>
     * @param value The fPS to set.
     * @return This builder for chaining.
     */
    public Builder setFPS(int value) {
      bitField0_ |= 0x00000040;
      fPS_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 FPS = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearFPS() {
      bitField0_ = (bitField0_ & ~0x00000040);
      fPS_ = 0;
      onChanged();
      return this;
    }

    private int bitRate_ ;
    /**
     * <code>optional uint32 BitRate = 8;</code>
     * @return Whether the bitRate field is set.
     */
    @java.lang.Override
    public boolean hasBitRate() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional uint32 BitRate = 8;</code>
     * @return The bitRate.
     */
    @java.lang.Override
    public int getBitRate() {
      return bitRate_;
    }
    /**
     * <code>optional uint32 BitRate = 8;</code>
     * @param value The bitRate to set.
     * @return This builder for chaining.
     */
    public Builder setBitRate(int value) {
      bitField0_ |= 0x00000080;
      bitRate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 BitRate = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearBitRate() {
      bitField0_ = (bitField0_ & ~0x00000080);
      bitRate_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object format_ = "";
    /**
     * <code>optional string Format = 9;</code>
     * @return Whether the format field is set.
     */
    public boolean hasFormat() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional string Format = 9;</code>
     * @return The format.
     */
    public java.lang.String getFormat() {
      java.lang.Object ref = format_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        format_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string Format = 9;</code>
     * @return The bytes for format.
     */
    public com.google.protobuf.ByteString
        getFormatBytes() {
      java.lang.Object ref = format_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        format_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string Format = 9;</code>
     * @param value The format to set.
     * @return This builder for chaining.
     */
    public Builder setFormat(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      format_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string Format = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearFormat() {
      bitField0_ = (bitField0_ & ~0x00000100);
      format_ = getDefaultInstance().getFormat();
      onChanged();
      return this;
    }
    /**
     * <code>optional string Format = 9;</code>
     * @param value The bytes for format to set.
     * @return This builder for chaining.
     */
    public Builder setFormatBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000100;
      format_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mediaType_ = "";
    /**
     * <code>optional string MediaType = 10;</code>
     * @return Whether the mediaType field is set.
     */
    public boolean hasMediaType() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional string MediaType = 10;</code>
     * @return The mediaType.
     */
    public java.lang.String getMediaType() {
      java.lang.Object ref = mediaType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mediaType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string MediaType = 10;</code>
     * @return The bytes for mediaType.
     */
    public com.google.protobuf.ByteString
        getMediaTypeBytes() {
      java.lang.Object ref = mediaType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mediaType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string MediaType = 10;</code>
     * @param value The mediaType to set.
     * @return This builder for chaining.
     */
    public Builder setMediaType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
      mediaType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string MediaType = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearMediaType() {
      bitField0_ = (bitField0_ & ~0x00000200);
      mediaType_ = getDefaultInstance().getMediaType();
      onChanged();
      return this;
    }
    /**
     * <code>optional string MediaType = 10;</code>
     * @param value The bytes for mediaType to set.
     * @return This builder for chaining.
     */
    public Builder setMediaTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000200;
      mediaType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mediaTag_ = "";
    /**
     * <code>optional string MediaTag = 11;</code>
     * @return Whether the mediaTag field is set.
     */
    public boolean hasMediaTag() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>optional string MediaTag = 11;</code>
     * @return The mediaTag.
     */
    public java.lang.String getMediaTag() {
      java.lang.Object ref = mediaTag_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mediaTag_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string MediaTag = 11;</code>
     * @return The bytes for mediaTag.
     */
    public com.google.protobuf.ByteString
        getMediaTagBytes() {
      java.lang.Object ref = mediaTag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mediaTag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string MediaTag = 11;</code>
     * @param value The mediaTag to set.
     * @return This builder for chaining.
     */
    public Builder setMediaTag(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
      mediaTag_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string MediaTag = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearMediaTag() {
      bitField0_ = (bitField0_ & ~0x00000400);
      mediaTag_ = getDefaultInstance().getMediaTag();
      onChanged();
      return this;
    }
    /**
     * <code>optional string MediaTag = 11;</code>
     * @param value The bytes for mediaTag to set.
     * @return This builder for chaining.
     */
    public Builder setMediaTagBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000400;
      mediaTag_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mediaSecondTag_ = "";
    /**
     * <code>optional string MediaSecondTag = 12;</code>
     * @return Whether the mediaSecondTag field is set.
     */
    public boolean hasMediaSecondTag() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>optional string MediaSecondTag = 12;</code>
     * @return The mediaSecondTag.
     */
    public java.lang.String getMediaSecondTag() {
      java.lang.Object ref = mediaSecondTag_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mediaSecondTag_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string MediaSecondTag = 12;</code>
     * @return The bytes for mediaSecondTag.
     */
    public com.google.protobuf.ByteString
        getMediaSecondTagBytes() {
      java.lang.Object ref = mediaSecondTag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mediaSecondTag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string MediaSecondTag = 12;</code>
     * @param value The mediaSecondTag to set.
     * @return This builder for chaining.
     */
    public Builder setMediaSecondTag(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
      mediaSecondTag_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string MediaSecondTag = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearMediaSecondTag() {
      bitField0_ = (bitField0_ & ~0x00000800);
      mediaSecondTag_ = getDefaultInstance().getMediaSecondTag();
      onChanged();
      return this;
    }
    /**
     * <code>optional string MediaSecondTag = 12;</code>
     * @param value The bytes for mediaSecondTag to set.
     * @return This builder for chaining.
     */
    public Builder setMediaSecondTagBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000800;
      mediaSecondTag_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mediaLang_ = "";
    /**
     * <code>optional string MediaLang = 13;</code>
     * @return Whether the mediaLang field is set.
     */
    public boolean hasMediaLang() {
      return ((bitField0_ & 0x00001000) != 0);
    }
    /**
     * <code>optional string MediaLang = 13;</code>
     * @return The mediaLang.
     */
    public java.lang.String getMediaLang() {
      java.lang.Object ref = mediaLang_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mediaLang_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string MediaLang = 13;</code>
     * @return The bytes for mediaLang.
     */
    public com.google.protobuf.ByteString
        getMediaLangBytes() {
      java.lang.Object ref = mediaLang_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mediaLang_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string MediaLang = 13;</code>
     * @param value The mediaLang to set.
     * @return This builder for chaining.
     */
    public Builder setMediaLang(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
      mediaLang_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string MediaLang = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearMediaLang() {
      bitField0_ = (bitField0_ & ~0x00001000);
      mediaLang_ = getDefaultInstance().getMediaLang();
      onChanged();
      return this;
    }
    /**
     * <code>optional string MediaLang = 13;</code>
     * @param value The bytes for mediaLang to set.
     * @return This builder for chaining.
     */
    public Builder setMediaLangBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00001000;
      mediaLang_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object downLoadURL_ = "";
    /**
     * <code>optional string DownLoadURL = 14;</code>
     * @return Whether the downLoadURL field is set.
     */
    public boolean hasDownLoadURL() {
      return ((bitField0_ & 0x00002000) != 0);
    }
    /**
     * <code>optional string DownLoadURL = 14;</code>
     * @return The downLoadURL.
     */
    public java.lang.String getDownLoadURL() {
      java.lang.Object ref = downLoadURL_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        downLoadURL_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string DownLoadURL = 14;</code>
     * @return The bytes for downLoadURL.
     */
    public com.google.protobuf.ByteString
        getDownLoadURLBytes() {
      java.lang.Object ref = downLoadURL_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        downLoadURL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string DownLoadURL = 14;</code>
     * @param value The downLoadURL to set.
     * @return This builder for chaining.
     */
    public Builder setDownLoadURL(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
      downLoadURL_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string DownLoadURL = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearDownLoadURL() {
      bitField0_ = (bitField0_ & ~0x00002000);
      downLoadURL_ = getDefaultInstance().getDownLoadURL();
      onChanged();
      return this;
    }
    /**
     * <code>optional string DownLoadURL = 14;</code>
     * @param value The bytes for downLoadURL to set.
     * @return This builder for chaining.
     */
    public Builder setDownLoadURLBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00002000;
      downLoadURL_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>optional string Status = 15;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00004000) != 0);
    }
    /**
     * <code>optional string Status = 15;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string Status = 15;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string Status = 15;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string Status = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00004000);
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <code>optional string Status = 15;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00004000;
      status_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object failedReason_ = "";
    /**
     * <code>optional string FailedReason = 16;</code>
     * @return Whether the failedReason field is set.
     */
    public boolean hasFailedReason() {
      return ((bitField0_ & 0x00008000) != 0);
    }
    /**
     * <code>optional string FailedReason = 16;</code>
     * @return The failedReason.
     */
    public java.lang.String getFailedReason() {
      java.lang.Object ref = failedReason_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        failedReason_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string FailedReason = 16;</code>
     * @return The bytes for failedReason.
     */
    public com.google.protobuf.ByteString
        getFailedReasonBytes() {
      java.lang.Object ref = failedReason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        failedReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string FailedReason = 16;</code>
     * @param value The failedReason to set.
     * @return This builder for chaining.
     */
    public Builder setFailedReason(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
      failedReason_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string FailedReason = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearFailedReason() {
      bitField0_ = (bitField0_ & ~0x00008000);
      failedReason_ = getDefaultInstance().getFailedReason();
      onChanged();
      return this;
    }
    /**
     * <code>optional string FailedReason = 16;</code>
     * @param value The bytes for failedReason to set.
     * @return This builder for chaining.
     */
    public Builder setFailedReasonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00008000;
      failedReason_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MediaInfo)
  }

  // @@protoc_insertion_point(class_scope:MediaInfo)
  private static final com.mediaassetsdk.MediaInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mediaassetsdk.MediaInfo();
  }

  public static com.mediaassetsdk.MediaInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MediaInfo>
      PARSER = new com.google.protobuf.AbstractParser<MediaInfo>() {
    @java.lang.Override
    public MediaInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MediaInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MediaInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MediaInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mediaassetsdk.MediaInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

