// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MediaAsset.proto

package com.mediaassetsdk;

public interface MediaMetaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MediaMeta)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string MediaType = 1;</code>
   * @return Whether the mediaType field is set.
   */
  boolean hasMediaType();
  /**
   * <code>optional string MediaType = 1;</code>
   * @return The mediaType.
   */
  java.lang.String getMediaType();
  /**
   * <code>optional string MediaType = 1;</code>
   * @return The bytes for mediaType.
   */
  com.google.protobuf.ByteString
      getMediaTypeBytes();

  /**
   * <code>optional string MediaTag = 2;</code>
   * @return Whether the mediaTag field is set.
   */
  boolean hasMediaTag();
  /**
   * <code>optional string MediaTag = 2;</code>
   * @return The mediaTag.
   */
  java.lang.String getMediaTag();
  /**
   * <code>optional string MediaTag = 2;</code>
   * @return The bytes for mediaTag.
   */
  com.google.protobuf.ByteString
      getMediaTagBytes();

  /**
   * <code>optional string MediaSecondTag = 3;</code>
   * @return Whether the mediaSecondTag field is set.
   */
  boolean hasMediaSecondTag();
  /**
   * <code>optional string MediaSecondTag = 3;</code>
   * @return The mediaSecondTag.
   */
  java.lang.String getMediaSecondTag();
  /**
   * <code>optional string MediaSecondTag = 3;</code>
   * @return The bytes for mediaSecondTag.
   */
  com.google.protobuf.ByteString
      getMediaSecondTagBytes();

  /**
   * <code>optional string MediaLang = 4;</code>
   * @return Whether the mediaLang field is set.
   */
  boolean hasMediaLang();
  /**
   * <code>optional string MediaLang = 4;</code>
   * @return The mediaLang.
   */
  java.lang.String getMediaLang();
  /**
   * <code>optional string MediaLang = 4;</code>
   * @return The bytes for mediaLang.
   */
  com.google.protobuf.ByteString
      getMediaLangBytes();
}
