// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MediaAsset.proto

package com.mediaassetsdk;

public interface UploadPartResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UploadPartResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string RequestID = 1;</code>
   * @return Whether the requestID field is set.
   */
  boolean hasRequestID();
  /**
   * <code>optional string RequestID = 1;</code>
   * @return The requestID.
   */
  java.lang.String getRequestID();
  /**
   * <code>optional string RequestID = 1;</code>
   * @return The bytes for requestID.
   */
  com.google.protobuf.ByteString
      getRequestIDBytes();

  /**
   * <code>optional .Error Error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>optional .Error Error = 2;</code>
   * @return The error.
   */
  com.mediaassetsdk.Error getError();
  /**
   * <code>optional .Error Error = 2;</code>
   */
  com.mediaassetsdk.ErrorOrBuilder getErrorOrBuilder();

  /**
   * <code>optional string ETag = 3;</code>
   * @return Whether the eTag field is set.
   */
  boolean hasETag();
  /**
   * <code>optional string ETag = 3;</code>
   * @return The eTag.
   */
  java.lang.String getETag();
  /**
   * <code>optional string ETag = 3;</code>
   * @return The bytes for eTag.
   */
  com.google.protobuf.ByteString
      getETagBytes();
}
