// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MediaAsset.proto

package com.mediaassetsdk;

/**
 * Protobuf type {@code UploadPartRequest}
 */
public final class UploadPartRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:UploadPartRequest)
    UploadPartRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UploadPartRequest.newBuilder() to construct.
  private UploadPartRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UploadPartRequest() {
    buffer_ = com.google.protobuf.ByteString.EMPTY;
    bucket_ = "";
    key_ = "";
    uploadID_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UploadPartRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UploadPartRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            bitField0_ |= 0x00000001;
            buffer_ = input.readBytes();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            partNUmber_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000004;
            bucket_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000008;
            key_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000010;
            uploadID_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mediaassetsdk.MediaAsset.internal_static_UploadPartRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mediaassetsdk.MediaAsset.internal_static_UploadPartRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mediaassetsdk.UploadPartRequest.class, com.mediaassetsdk.UploadPartRequest.Builder.class);
  }

  private int bitField0_;
  public static final int BUFFER_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString buffer_;
  /**
   * <code>optional bytes Buffer = 1;</code>
   * @return Whether the buffer field is set.
   */
  @java.lang.Override
  public boolean hasBuffer() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional bytes Buffer = 1;</code>
   * @return The buffer.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBuffer() {
    return buffer_;
  }

  public static final int PARTNUMBER_FIELD_NUMBER = 2;
  private int partNUmber_;
  /**
   * <code>optional int32 PartNUmber = 2;</code>
   * @return Whether the partNUmber field is set.
   */
  @java.lang.Override
  public boolean hasPartNUmber() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int32 PartNUmber = 2;</code>
   * @return The partNUmber.
   */
  @java.lang.Override
  public int getPartNUmber() {
    return partNUmber_;
  }

  public static final int BUCKET_FIELD_NUMBER = 3;
  private volatile java.lang.Object bucket_;
  /**
   * <code>optional string Bucket = 3;</code>
   * @return Whether the bucket field is set.
   */
  @java.lang.Override
  public boolean hasBucket() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string Bucket = 3;</code>
   * @return The bucket.
   */
  @java.lang.Override
  public java.lang.String getBucket() {
    java.lang.Object ref = bucket_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bucket_ = s;
      return s;
    }
  }
  /**
   * <code>optional string Bucket = 3;</code>
   * @return The bytes for bucket.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBucketBytes() {
    java.lang.Object ref = bucket_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bucket_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KEY_FIELD_NUMBER = 4;
  private volatile java.lang.Object key_;
  /**
   * <code>optional string Key = 4;</code>
   * @return Whether the key field is set.
   */
  @java.lang.Override
  public boolean hasKey() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string Key = 4;</code>
   * @return The key.
   */
  @java.lang.Override
  public java.lang.String getKey() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      key_ = s;
      return s;
    }
  }
  /**
   * <code>optional string Key = 4;</code>
   * @return The bytes for key.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeyBytes() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      key_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPLOADID_FIELD_NUMBER = 5;
  private volatile java.lang.Object uploadID_;
  /**
   * <code>optional string UploadID = 5;</code>
   * @return Whether the uploadID field is set.
   */
  @java.lang.Override
  public boolean hasUploadID() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string UploadID = 5;</code>
   * @return The uploadID.
   */
  @java.lang.Override
  public java.lang.String getUploadID() {
    java.lang.Object ref = uploadID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uploadID_ = s;
      return s;
    }
  }
  /**
   * <code>optional string UploadID = 5;</code>
   * @return The bytes for uploadID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUploadIDBytes() {
    java.lang.Object ref = uploadID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uploadID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBytes(1, buffer_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, partNUmber_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, bucket_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, key_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, uploadID_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, buffer_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, partNUmber_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, bucket_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, key_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, uploadID_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mediaassetsdk.UploadPartRequest)) {
      return super.equals(obj);
    }
    com.mediaassetsdk.UploadPartRequest other = (com.mediaassetsdk.UploadPartRequest) obj;

    if (hasBuffer() != other.hasBuffer()) return false;
    if (hasBuffer()) {
      if (!getBuffer()
          .equals(other.getBuffer())) return false;
    }
    if (hasPartNUmber() != other.hasPartNUmber()) return false;
    if (hasPartNUmber()) {
      if (getPartNUmber()
          != other.getPartNUmber()) return false;
    }
    if (hasBucket() != other.hasBucket()) return false;
    if (hasBucket()) {
      if (!getBucket()
          .equals(other.getBucket())) return false;
    }
    if (hasKey() != other.hasKey()) return false;
    if (hasKey()) {
      if (!getKey()
          .equals(other.getKey())) return false;
    }
    if (hasUploadID() != other.hasUploadID()) return false;
    if (hasUploadID()) {
      if (!getUploadID()
          .equals(other.getUploadID())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBuffer()) {
      hash = (37 * hash) + BUFFER_FIELD_NUMBER;
      hash = (53 * hash) + getBuffer().hashCode();
    }
    if (hasPartNUmber()) {
      hash = (37 * hash) + PARTNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPartNUmber();
    }
    if (hasBucket()) {
      hash = (37 * hash) + BUCKET_FIELD_NUMBER;
      hash = (53 * hash) + getBucket().hashCode();
    }
    if (hasKey()) {
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
    }
    if (hasUploadID()) {
      hash = (37 * hash) + UPLOADID_FIELD_NUMBER;
      hash = (53 * hash) + getUploadID().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mediaassetsdk.UploadPartRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mediaassetsdk.UploadPartRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mediaassetsdk.UploadPartRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mediaassetsdk.UploadPartRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mediaassetsdk.UploadPartRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mediaassetsdk.UploadPartRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mediaassetsdk.UploadPartRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mediaassetsdk.UploadPartRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mediaassetsdk.UploadPartRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.mediaassetsdk.UploadPartRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mediaassetsdk.UploadPartRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mediaassetsdk.UploadPartRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mediaassetsdk.UploadPartRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UploadPartRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UploadPartRequest)
      com.mediaassetsdk.UploadPartRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mediaassetsdk.MediaAsset.internal_static_UploadPartRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mediaassetsdk.MediaAsset.internal_static_UploadPartRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mediaassetsdk.UploadPartRequest.class, com.mediaassetsdk.UploadPartRequest.Builder.class);
    }

    // Construct using com.mediaassetsdk.UploadPartRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      buffer_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      partNUmber_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      bucket_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      key_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      uploadID_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mediaassetsdk.MediaAsset.internal_static_UploadPartRequest_descriptor;
    }

    @java.lang.Override
    public com.mediaassetsdk.UploadPartRequest getDefaultInstanceForType() {
      return com.mediaassetsdk.UploadPartRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.mediaassetsdk.UploadPartRequest build() {
      com.mediaassetsdk.UploadPartRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mediaassetsdk.UploadPartRequest buildPartial() {
      com.mediaassetsdk.UploadPartRequest result = new com.mediaassetsdk.UploadPartRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.buffer_ = buffer_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.partNUmber_ = partNUmber_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.bucket_ = bucket_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.key_ = key_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.uploadID_ = uploadID_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mediaassetsdk.UploadPartRequest) {
        return mergeFrom((com.mediaassetsdk.UploadPartRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mediaassetsdk.UploadPartRequest other) {
      if (other == com.mediaassetsdk.UploadPartRequest.getDefaultInstance()) return this;
      if (other.hasBuffer()) {
        setBuffer(other.getBuffer());
      }
      if (other.hasPartNUmber()) {
        setPartNUmber(other.getPartNUmber());
      }
      if (other.hasBucket()) {
        bitField0_ |= 0x00000004;
        bucket_ = other.bucket_;
        onChanged();
      }
      if (other.hasKey()) {
        bitField0_ |= 0x00000008;
        key_ = other.key_;
        onChanged();
      }
      if (other.hasUploadID()) {
        bitField0_ |= 0x00000010;
        uploadID_ = other.uploadID_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.mediaassetsdk.UploadPartRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.mediaassetsdk.UploadPartRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString buffer_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes Buffer = 1;</code>
     * @return Whether the buffer field is set.
     */
    @java.lang.Override
    public boolean hasBuffer() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes Buffer = 1;</code>
     * @return The buffer.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBuffer() {
      return buffer_;
    }
    /**
     * <code>optional bytes Buffer = 1;</code>
     * @param value The buffer to set.
     * @return This builder for chaining.
     */
    public Builder setBuffer(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      buffer_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes Buffer = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBuffer() {
      bitField0_ = (bitField0_ & ~0x00000001);
      buffer_ = getDefaultInstance().getBuffer();
      onChanged();
      return this;
    }

    private int partNUmber_ ;
    /**
     * <code>optional int32 PartNUmber = 2;</code>
     * @return Whether the partNUmber field is set.
     */
    @java.lang.Override
    public boolean hasPartNUmber() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 PartNUmber = 2;</code>
     * @return The partNUmber.
     */
    @java.lang.Override
    public int getPartNUmber() {
      return partNUmber_;
    }
    /**
     * <code>optional int32 PartNUmber = 2;</code>
     * @param value The partNUmber to set.
     * @return This builder for chaining.
     */
    public Builder setPartNUmber(int value) {
      bitField0_ |= 0x00000002;
      partNUmber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 PartNUmber = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPartNUmber() {
      bitField0_ = (bitField0_ & ~0x00000002);
      partNUmber_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object bucket_ = "";
    /**
     * <code>optional string Bucket = 3;</code>
     * @return Whether the bucket field is set.
     */
    public boolean hasBucket() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string Bucket = 3;</code>
     * @return The bucket.
     */
    public java.lang.String getBucket() {
      java.lang.Object ref = bucket_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bucket_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string Bucket = 3;</code>
     * @return The bytes for bucket.
     */
    public com.google.protobuf.ByteString
        getBucketBytes() {
      java.lang.Object ref = bucket_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bucket_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string Bucket = 3;</code>
     * @param value The bucket to set.
     * @return This builder for chaining.
     */
    public Builder setBucket(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      bucket_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string Bucket = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBucket() {
      bitField0_ = (bitField0_ & ~0x00000004);
      bucket_ = getDefaultInstance().getBucket();
      onChanged();
      return this;
    }
    /**
     * <code>optional string Bucket = 3;</code>
     * @param value The bytes for bucket to set.
     * @return This builder for chaining.
     */
    public Builder setBucketBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000004;
      bucket_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object key_ = "";
    /**
     * <code>optional string Key = 4;</code>
     * @return Whether the key field is set.
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string Key = 4;</code>
     * @return The key.
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string Key = 4;</code>
     * @return The bytes for key.
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string Key = 4;</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      key_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string Key = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      bitField0_ = (bitField0_ & ~0x00000008);
      key_ = getDefaultInstance().getKey();
      onChanged();
      return this;
    }
    /**
     * <code>optional string Key = 4;</code>
     * @param value The bytes for key to set.
     * @return This builder for chaining.
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000008;
      key_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object uploadID_ = "";
    /**
     * <code>optional string UploadID = 5;</code>
     * @return Whether the uploadID field is set.
     */
    public boolean hasUploadID() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string UploadID = 5;</code>
     * @return The uploadID.
     */
    public java.lang.String getUploadID() {
      java.lang.Object ref = uploadID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uploadID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string UploadID = 5;</code>
     * @return The bytes for uploadID.
     */
    public com.google.protobuf.ByteString
        getUploadIDBytes() {
      java.lang.Object ref = uploadID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uploadID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string UploadID = 5;</code>
     * @param value The uploadID to set.
     * @return This builder for chaining.
     */
    public Builder setUploadID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      uploadID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string UploadID = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearUploadID() {
      bitField0_ = (bitField0_ & ~0x00000010);
      uploadID_ = getDefaultInstance().getUploadID();
      onChanged();
      return this;
    }
    /**
     * <code>optional string UploadID = 5;</code>
     * @param value The bytes for uploadID to set.
     * @return This builder for chaining.
     */
    public Builder setUploadIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000010;
      uploadID_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:UploadPartRequest)
  }

  // @@protoc_insertion_point(class_scope:UploadPartRequest)
  private static final com.mediaassetsdk.UploadPartRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mediaassetsdk.UploadPartRequest();
  }

  public static com.mediaassetsdk.UploadPartRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UploadPartRequest>
      PARSER = new com.google.protobuf.AbstractParser<UploadPartRequest>() {
    @java.lang.Override
    public UploadPartRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UploadPartRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UploadPartRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UploadPartRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mediaassetsdk.UploadPartRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

